# SDRF Extraction Pipeline Kaggle: Harmonizing the Data of Your Data

rules + LLM + normalisation (tbd iterative)
plain langchain, no dspy

In [1]:
import time
from datetime import timedelta
start_time = time.monotonic()

# Dependencies, configuration, LocalAI

In [2]:
# ── Kaggle secrets ───────────────────────────────────────────────────────────
import os
try:
    from kaggle_secrets import UserSecretsClient
    user_secrets = UserSecretsClient()
    def get_secret_safe(name, default=None):
        try: return user_secrets.get_secret(name)
        except Exception: return default
    api_key  = get_secret_safe('LLM_API_KEY', 'sk-dummy')
    api_base = get_secret_safe('LLM_API_BASE', None)
    LLM_MODEL = get_secret_safe("LLM_MODEL", None)
    # Force into environment (CRITICAL)
    os.environ["OPENAI_API_KEY"] = api_key
    # (Optional but helps LiteLLM routing)
    os.environ["OPENAI_API_BASE"] = "https://api.openai.com/v1"
except Exception as x:
    print(x)
    api_key = None
    api_base = None
    LLM_MODEL = None
if LLM_MODEL is None:
    api_key = 'sk-dummy'
    api_base = "http://127.0.0.1:8080/v1"
    CONTEXT_SIZE = 24576
    # Tested models:
    # gemma-3-4b-it @ kaggle (GPU P100)
    # medgemma-4b-it @ kaggle (GPU P100)
    # deepseek-coder-v2-lite-instruct @ kaggle (GPU T4 x 2)
    LLM_MODEL = "gemma-3-4b-it"

print(f'api_base={api_base}, api_key={api_key[:4]}, model={LLM_MODEL}')

api_base=http://127.0.0.1:8080/v1, api_key=sk-d, model=gemma-3-4b-it

In [3]:
LAUNCH_LOCAL_AI = api_base is None or api_base == "http://127.0.0.1:8080/v1"
LAUNCH_LOCAL_AI

True

## LocalAI Server

In [4]:
# Create tmp folder to be used as a larger scratch space
from pathlib import Path

TMP_DIR = Path('../tmp')
TMP_DIR.mkdir(exist_ok=True)

In [5]:
%%bash
# Download and make executable the local-ai binary (https://github.com/mudler/LocalAI/releases)
cd ../tmp
if [ ! -f ./local-ai-* ]; then
    wget -q https://github.com/mudler/LocalAI/releases/download/v4.0.0/local-ai-v4.0.0-linux-amd64
fi
chmod +x local-ai-*

In [6]:
%%bash
# Download Model Gallery
mkdir /kaggle/tmp/models
cd /kaggle/tmp/models
git clone --filter=blob:none --sparse https://github.com/mudler/LocalAI.git
cd LocalAI
git sparse-checkout set gallery

Cloning into 'LocalAI'...

In [7]:
import subprocess
import requests
import time
import signal
import os

# Use modified local model gallery
os.environ["GALLERIES"] = '[{"name":"localai", "url":"file:///kaggle/tmp/models/LocalAI/gallery/index.updated.yaml"}]'

class LocalAIServer:
    def __init__(self, binary_path: str, model_name: str, host: str = "127.0.0.1", port: int = 8080):
        self.binary_path = binary_path
        self.model_name = model_name
        self.host = host
        self.port = port
        self.proc = None

    def start(self):
        """Start LocalAI as a subprocess."""
        if self.proc is not None:
            raise RuntimeError("Server already running")
        
        self.proc = subprocess.Popen(
            [self.binary_path, "run", self.model_name, "--disable-web-ui"],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True
        )
        self._wait_until_ready()

    def _wait_until_ready(self, timeout: int = 1200):
        """Poll the server until it responds or timeout."""
        url = f"http://{self.host}:{self.port}/v1/models"
        start_time = time.time()
        while True:
            try:
                res = requests.get(url, timeout=1)
                if res.status_code == 200:
                    print("LocalAI server is ready!")
                    break
            except requests.RequestException:
                pass  # server not ready yet
            if time.time() - start_time > timeout:
                raise TimeoutError("LocalAI server did not start in time")
            time.sleep(1)

    def stop(self):
        """Stop the LocalAI server."""
        if self.proc:
            self.proc.terminate()  # SIGTERM
            try:
                self.proc.wait(timeout=5)
            except subprocess.TimeoutExpired:
                self.proc.kill()   # SIGKILL if needed
                self.proc.wait()
            self.proc = None
            print("LocalAI server stopped.")

In [8]:
# Set the context_size for the selected model from the local model gallery

import yaml

def set_context_size(yaml_path, model_name, context_size, output_path=None):
    with open(yaml_path, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)

    if not isinstance(data, list):
        raise ValueError("Expected a list of models")

    found = False

    for model in data:
        if model.get("name") == model_name:
            # Ensure overrides block exists
            overrides = model.get("overrides")
            if overrides is None:
                overrides = {}
                model["overrides"] = overrides

            # Set / update context_size
            overrides["context_size"] = context_size

            found = True
            break

    if not found:
        raise ValueError(f"Model '{model_name}' not found")

    out = output_path or yaml_path
    with open(out, "w", encoding="utf-8") as f:
        yaml.safe_dump(data, f, sort_keys=False)

    return out

set_context_size(
    yaml_path = "/kaggle/tmp/models/LocalAI/gallery/index.yaml",
    model_name = LLM_MODEL,
    context_size = CONTEXT_SIZE,
    output_path = "/kaggle/tmp/models/LocalAI/gallery/index.updated.yaml"
)

'/kaggle/tmp/models/LocalAI/gallery/index.updated.yaml'

In [9]:
if LAUNCH_LOCAL_AI:
    server = LocalAIServer("/kaggle/tmp/local-ai-v4.0.0-linux-amd64", LLM_MODEL)
    os.chdir( "/kaggle/tmp")
    server.start()

    """"
    # Now the server is ready, you can query it:
    res = requests.post(
        "http://127.0.0.1:8080/v1/chat/completions",
        json={
            "model": LLM_MODEL,
            "messages": [{"role": "user", "content": "Explain LLMs in one sentence."}]
        },
        timeout=1200
    )
    print(res.json())
    """
else:
    """
    res = requests.post(
        f"{api_base}/chat/completions",
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json"
        },        
        json={
            "model": LLM_MODEL,
            "messages": [{"role": "user", "content": "Explain LLMs in one sentence."}]
        },
        timeout=1200
    )    
    print(res.status_code)
    print(res.text)
    """
    server = None

LocalAI server is ready!

In [10]:
import logging

logging.basicConfig(level=logging.INFO,
                    format='%(asctime)s %(levelname)s %(message)s')
log = logging.getLogger('sdrf')

In [11]:
print("CWD:", os.getcwd())
os.chdir("/kaggle/working")
!pwd

CWD: /kaggle/tmp
/kaggle/working

##  Install & Import modelmess

In [12]:
%pip install -q langchain langchain-openai langchain-core pydantic openai sdrf-pipelines[all] sdrf-pipelines[ontology] PyYAML 
# check if ols dep is in
from sdrf_pipelines.ols.ols import OlsClient, OLS_AVAILABLE
print(OLS_AVAILABLE)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.5/88.5 kB 5.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 506.7/506.7 kB 22.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 58.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 80.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 615.4/615.4 kB 38.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 569.0/569.0 kB 38.2 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.

2026-03-30 11:12:34,609 INFO NumExpr defaulting to 4 threads.

True

In [13]:
import sys

os.chdir("/kaggle/working")
!cd /kaggle/working

repo_url = 'https://github.com/vedina/modelmess.git'
repo_dir = '/kaggle/working/modelmess'

#branch = "iterative"
branch = "main"

if os.path.exists(repo_dir):
    print("Repo already exists. Pulling latest changes...")
    !cd {repo_dir} && git pull
else:
    print(f"Cloning repo (branch: {branch})...")
    !git clone --branch {branch} --single-branch {repo_url}

# Add the src folder inside the repo to Python path
SOURCE_DIR = f"{repo_dir}/sdrf_pipeline"
# Remove any old modelmess paths (important)
sys.path = [p for p in sys.path if "modelmess" not in p]
# Add correct one at highest priority
sys.path.insert(0,SOURCE_DIR)

# Verify import
from src.rules_0000 import PaperJSON

print('modelmess sdrf_pipeline imported OK')
%cd {SOURCE_DIR}
!pwd

Repo already exists. Pulling latest changes...
Already up to date.
modelmess sdrf_pipeline imported OK
/kaggle/working/modelmess/sdrf_pipeline
/kaggle/working/modelmess/sdrf_pipeline

## Configuration

In [14]:
ON_KAGGLE = Path('/kaggle').exists()

# ── LLM config ───────────────────────────────────────────────────────────────
LLM_API_BASE = api_base           # from Cell 0
LLM_API_KEY  = api_key
LLM_MODEL    = LLM_MODEL
RUN = 1

LLM_BACKEND = 'openai_compat'

TEMPERATURE = 0

BASE_DIR       = Path('/kaggle/input/competitions/harmonizing-the-data-of-your-data')
TRAIN_TEXT_DIR = BASE_DIR / 'Training_PubText' / 'PubText'
TRAIN_SDRF_DIR = BASE_DIR / 'Training_SDRFs' / 'HarmonizedFiles'
TEST_TEXT_DIR  = BASE_DIR / 'Test PubText' / 'Test PubText'
SAMPLE_SUB     = BASE_DIR / 'SampleSubmission.csv'
OUTPUT_DIR     = Path(f'/kaggle/working/output_sdrfs/{LLM_MODEL}/T{TEMPERATURE}/R{RUN}')
OUTPUT_DIR_RULES = Path(f'/kaggle/working/output_sdrfs/rules_0000')

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
OUTPUT_DIR_RULES.mkdir(parents=True, exist_ok=True)

SUBMISSION = "/kaggle/working/submission.csv"

print(f'Backend : {LLM_BACKEND}')
print(f'URL     : {LLM_API_BASE}')
print(f'Model   : {LLM_MODEL}')
print(f'Kaggle  : {ON_KAGGLE}')
print(f'Output  : {OUTPUT_DIR}')

Backend : openai_compat
URL     : http://127.0.0.1:8080/v1
Model   : gemma-3-4b-it
Kaggle  : True
Output  : /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1

# Run extraction pipeline

In [15]:
!python main_fill.py --help

usage: main_fill.py [-h] [--pattern GLOB] [--stage {rules,llm,both}]
                    [--rules-only] [--rules-dir RULES_DIR] [--llm-dir LLM_DIR]
                    [--fill-from DIR] [--api-key API_KEY]
                    [--base-url BASE_URL] [--model MODEL]
                    [--max-tokens MAX_TOKENS] [--context-limit TOKENS]
                    [--no-dedup] [--prompts TOML] [--dump-prompts TOML]
                    [--verbose]
                    [input]

SDRF extraction -- rules + LLM gap-fill pipeline.

positional arguments:
  input                 Paper JSON source. Two forms: directory/ -> all *.json
                        files in that folder path/to/file.json -> single file
                        Use --pattern to filter files inside a directory. Not
                        required when using --dump-prompts.

options:
  -h, --help            show this help message and exit
  --pattern GLOB        Glob pattern inside the input directory (default:
                        *.json). Example: --pattern 'PXD06*.json'
  --stage {rules,llm,both}
                        Which stage(s) to run (default: both).
  --rules-only          Alias for --stage rules (backwards compat).
  --rules-dir RULES_DIR
                        Folder for rule-based CSVs (default: output/rules).
  --llm-dir LLM_DIR     Folder for LLM-filled CSVs (default: output/llm).
  --fill-from DIR       For --stage llm: folder of pre-computed rule CSVs to
                        use as input. Falls back to --rules-dir if a file is
                        missing.
  --api-key API_KEY     LLM API key (default: OPENAI_API_KEY env).
  --base-url BASE_URL   OpenAI-compatible base URL.
  --model MODEL         Model name (default: gpt-4o-mini).
  --max-tokens MAX_TOKENS
                        Max LLM response tokens (default: 8192).
  --context-limit TOKENS
                        Context window size in tokens for trimming paper text
                        (default: None). Examples: 8192 for older models,
                        128000 for gpt-4o.
  --no-dedup            One LLM call per row (disables deduplication).
  --prompts TOML        Path to a TOML file overriding prompt templates.
                        Missing sections fall back to built-in defaults. Use
                        --dump-prompts to generate a starting file.
  --dump-prompts TOML   Write the current default prompts to TOML and exit.
                        Example: --dump-prompts prompts.toml
  --verbose, -v

SDRF Extraction -- two-stage pipeline
=====================================

Three stages, selectable via --stage:

  rules  -- rule-based extraction only; writes CSVs to --rules-dir
  llm    -- LLM gap-fill only; reads from --fill-from (or --rules-dir),
            writes to --llm-dir.  Requires paper JSONs for context.
  both   -- runs rules then llm in sequence (default)

Typical iterative workflow
--------------------------
  # 1. Bootstrap rule output once (fast, free)
  python main_fill.py papers/ --stage rules --rules-dir output/rules

  # 2. Dump default prompts to a file, then edit them
  python main_fill.py papers/ --dump-prompts my_prompts.toml

  # 3. Fill gaps with model A, custom prompts
  python main_fill.py papers/ --stage llm \
      --fill-from output/rules --llm-dir output/llm_gpt4o \
      --model gpt-4o --api-key $OPENAI_API_KEY \
      --prompts my_prompts.toml

  # 4. Fill gaps with model B (same rules, different output folder)
  python main_fill.py papers/ --stage llm \
      --fill-from output/rules --llm-dir output/llm_llama \
      --model llama3.1:70b --base-url http://localhost:11434/v1 --api-key ollama

  # 5. Re-fill a subset (pass a folder of specific rule CSVs)
  python main_fill.py papers/ --stage llm \
      --fill-from output/rules_subset --llm-dir output/llm_retry

## Bootstrap with rules 
adapted from https://www.kaggle.com/code/nikitagajbhiye30/harmonizing-0000

In [16]:
log.info(f"Writing into {OUTPUT_DIR}")
log.info(f"Reading from {TEST_TEXT_DIR}")
pxd_files_only = f"{TEST_TEXT_DIR}/PXD*.json"

#{TEST_TEXT_DIR}/PXD*.json
!python main_fill.py "{TEST_TEXT_DIR}" --pattern PXD*.json  --stage rules --rules-dir {OUTPUT_DIR_RULES}

2026-03-30 11:12:39,786 INFO Writing into /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1
2026-03-30 11:12:39,788 INFO Reading from /kaggle/input/competitions/harmonizing-the-data-of-your-data/Test PubText/Test PubText

11:12:39 [INFO] Pattern 'PXD*.json' in /kaggle/input/competitions/harmonizing-the-data-of-your-data/Test PubText/Test PubText -> 15 file(s)
11:12:39 [INFO] -- [1/15] PXD004010_PubText.json --
11:12:40 [INFO] [rules] PXD004010_PubText.json -> 10 rows, 54/73 fields filled in row 0
11:12:54 [INFO] Written 10 rows -> /kaggle/working/output_sdrfs/rules_0000/PXD004010_PubText.sdrf.csv
11:12:54 [INFO] -- [2/15] PXD016436_PubText.json --
11:12:54 [INFO] [rules] PXD016436_PubText.json -> 18 rows, 62/73 fields filled in row 0
11:12:54 [INFO] Written 18 rows -> /kaggle/working/output_sdrfs/rules_0000/PXD016436_PubText.sdrf.csv
11:12:54 [INFO] -- [3/15] PXD019519_PubText.json --
11:12:54 [INFO] [rules] PXD019519_PubText.json -> 6 rows, 64/73 fields filled in row 0
11:12:54 [INFO] Written 6 rows -> /kaggle/working/output_sdrfs/rules_0000/PXD019519_PubText.sdrf.csv
11:12:54 [INFO] -- [4/15] PXD025663_PubText.json --
11:12:54 [INFO] [rules] PXD025663_PubText.json -> 12 rows, 60/73 fields filled in row 0
11:12:54 [INFO] Written 12 rows -> /kaggle/working/output_sdrfs/rules_0000/PXD025663_PubText.sdrf.csv
11:12:54 [INFO] -- [5/15] PXD040582_PubText.json --
11:12:54 [INFO] [rules] PXD040582_PubText.json -> 24 rows, 64/73 fields filled in row 0
11:12:54 [INFO] Written 24 rows -> /kaggle/working/output_sdrfs/rules_0000/PXD040582_PubText.sdrf.csv
11:12:54 [INFO] -- [6/15] PXD050621_PubText.json --
11:12:54 [INFO] [rules] PXD050621_PubText.json -> 9 rows, 49/73 fields filled in row 0
11:12:54 [INFO] Written 9 rows -> /kaggle/working/output_sdrfs/rules_0000/PXD050621_PubText.sdrf.csv
11:12:54 [INFO] -- [7/15] PXD061009_PubText.json --
11:12:54 [INFO] [rules] PXD061009_PubText.json -> 2 rows, 61/73 fields filled in row 0
11:12:54 [INFO] Written 2 rows -> /kaggle/working/output_sdrfs/rules_0000/PXD061009_PubText.sdrf.csv
11:12:54 [INFO] -- [8/15] PXD061090_PubText.json --
11:12:54 [INFO] [rules] PXD061090_PubText.json -> 6 rows, 54/73 fields filled in row 0
11:12:54 [INFO] Written 6 rows -> /kaggle/working/output_sdrfs/rules_0000/PXD061090_PubText.sdrf.csv
11:12:54 [INFO] -- [9/15] PXD061136_PubText.json --
11:12:54 [INFO] [rules] PXD061136_PubText.json -> 2 rows, 55/73 fields filled in row 0
11:12:54 [INFO] Written 2 rows -> /kaggle/working/output_sdrfs/rules_0000/PXD061136_PubText.sdrf.csv
11:12:54 [INFO] -- [10/15] PXD061195_PubText.json --
11:12:54 [INFO] [rules] PXD061195_PubText.json -> 1376 rows, 65/73 fields filled in row 0
11:12:54 [INFO] Written 1376 rows -> /kaggle/working/output_sdrfs/rules_0000/PXD061195_PubText.sdrf.csv
11:12:54 [INFO] -- [11/15] PXD061285_PubText.json --
11:12:54 [INFO] [rules] PXD061285_PubText.json -> 60 rows, 59/73 fields filled in row 0
11:12:54 [INFO] Written 60 rows -> /kaggle/working/output_sdrfs/rules_0000/PXD061285_PubText.sdrf.csv
11:12:54 [INFO] -- [12/15] PXD062014_PubText.json --
11:12:55 [INFO] [rules] PXD062014_PubText.json -> 24 rows, 57/73 fields filled in row 0
11:12:55 [INFO] Written 24 rows -> /kaggle/working/output_sdrfs/rules_0000/PXD062014_PubText.sdrf.csv
11:12:55 [INFO] -- [13/15] PXD062469_PubText.json --
11:12:55 [INFO] [rules] PXD062469_PubText.json -> 32 rows, 60/73 fields filled in row 0
11:12:55 [INFO] Written 32 rows -> /kaggle/working/output_sdrfs/rules_0000/PXD062469_PubText.sdrf.csv
11:12:55 [INFO] -- [14/15] PXD062877_PubText.json --
11:12:55 [INFO] [rules] PXD062877_PubText.json -> 48 rows, 63/73 fields filled in row 0
11:12:55 [INFO] Written 48 rows -> /kaggle/working/output_sdrfs/rules_0000/PXD062877_PubText.sdrf.csv
11:12:55 [INFO] -- [15/15] PXD064564_PubText.json --
11:12:55 [INFO] [rules] PXD064564_PubText.json -> 30 rows, 57/73 fields filled in row 0
11:12:55 [INFO] Written 30 rows -> /kaggle/working/output_sdrfs/rules_0000/PXD064564_PubText.sdrf.csv

15/15 file(s) processed.
  Rules CSVs -> /kaggle/working/output_sdrfs/rules_0000/

In [17]:
MAX_TOKENS = 8192
#CONTEXT_LIMIT = CONTEXT_SIZE
CONTEXT_LIMIT = 22912
log.info(f"Writing into {OUTPUT_DIR}")
log.info(f"Reading from {TEST_TEXT_DIR}")
log.info(f"{api_base} {LLM_MODEL}")

2026-03-30 11:12:57,369 INFO Writing into /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1
2026-03-30 11:12:57,370 INFO Reading from /kaggle/input/competitions/harmonizing-the-data-of-your-data/Test PubText/Test PubText
2026-03-30 11:12:57,371 INFO http://127.0.0.1:8080/v1 gemma-3-4b-it

## Running LLM stage (gap filling)

> python main_fill.py papers/ --stage llm  --fill-from output/rules --llm-dir output/llm_gpt4o  --model gpt-4o --api-key $OPENAI_API_KEY

In [18]:
# Running second (LLM) stage (gap filling)
!python main_fill.py --stage llm --fill-from {OUTPUT_DIR_RULES} --max-tokens {MAX_TOKENS} --context-limit {CONTEXT_LIMIT} --llm-dir {OUTPUT_DIR}  --model {LLM_MODEL} --base-url {api_base} --api-key {api_key} --pattern PXD*.json "{TEST_TEXT_DIR}"

11:12:57 [INFO] Pattern 'PXD*.json' in /kaggle/input/competitions/harmonizing-the-data-of-your-data/Test PubText/Test PubText -> 15 file(s)
11:12:57 [INFO] -- [1/15] PXD004010_PubText.json --
11:12:57 [INFO] [llm] Loading rules CSV from /kaggle/working/output_sdrfs/rules_0000/PXD004010_PubText.sdrf.csv
11:13:04 [INFO] Deduplicated: 10 row(s) → 1 unique N/A pattern(s)
11:13:04 [INFO] Filling 62 field(s) for group of 10 row(s)…
11:13:04 [INFO] Chars: Paper9630 = M8027+A1493+T110
11:13:04 [INFO] Tokens: Paper2406 = M2006+A373+T27
11:13:04 [INFO] Context limit 22912 Available 10498 = CT22912-MT8192-FT4222
11:13:57 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:14:17 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:14:17 [INFO] Response received len=1848
11:14:17 [INFO] [llm]   PXD004010_PubText.json -> 45/73 fields filled in row 0 (+25 via LLM)
11:14:17 [INFO] Written 10 rows -> /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD004010_PubText.sdrf.csv
11:14:17 [INFO] -- [2/15] PXD016436_PubText.json --
11:14:17 [INFO] [llm] Loading rules CSV from /kaggle/working/output_sdrfs/rules_0000/PXD016436_PubText.sdrf.csv
11:14:17 [INFO] Deduplicated: 18 row(s) → 1 unique N/A pattern(s)
11:14:17 [INFO] Filling 54 field(s) for group of 18 row(s)…
11:14:17 [INFO] Chars: Paper6853 = M6201+A577+T75
11:14:17 [INFO] Tokens: Paper1712 = M1550+A144+T18
11:14:17 [INFO] Context limit 22912 Available 10907 = CT22912-MT8192-FT3813
11:14:38 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:14:56 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:14:56 [INFO] Response received len=1588
11:14:56 [INFO] [llm]   PXD016436_PubText.json -> 44/73 fields filled in row 0 (+16 via LLM)
11:14:56 [INFO] Written 18 rows -> /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD016436_PubText.sdrf.csv
11:14:56 [INFO] -- [3/15] PXD019519_PubText.json --
11:14:56 [INFO] [llm] Loading rules CSV from /kaggle/working/output_sdrfs/rules_0000/PXD019519_PubText.sdrf.csv
11:14:56 [INFO] Deduplicated: 6 row(s) → 1 unique N/A pattern(s)
11:14:56 [INFO] Filling 52 field(s) for group of 6 row(s)…
11:14:56 [INFO] Chars: Paper43567 = M42096+A1394+T77
11:14:56 [INFO] Tokens: Paper10891 = M10524+A348+T19
11:14:56 [INFO] Context limit 22912 Available 10966 = CT22912-MT8192-FT3754
11:15:36 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:16:13 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:16:13 [INFO] Response received len=1560
11:16:13 [INFO] [llm]   PXD019519_PubText.json -> 61/73 fields filled in row 0 (+31 via LLM)
11:16:13 [INFO] Written 6 rows -> /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD019519_PubText.sdrf.csv
11:16:13 [INFO] -- [4/15] PXD025663_PubText.json --
11:16:13 [INFO] [llm] Loading rules CSV from /kaggle/working/output_sdrfs/rules_0000/PXD025663_PubText.sdrf.csv
11:16:13 [INFO] Deduplicated: 12 row(s) → 1 unique N/A pattern(s)
11:16:13 [INFO] Filling 56 field(s) for group of 12 row(s)…
11:16:13 [INFO] Chars: Paper18589 = M16465+A2069+T55
11:16:13 [INFO] Tokens: Paper4646 = M4116+A517+T13
11:16:13 [INFO] Context limit 22912 Available 10759 = CT22912-MT8192-FT3961
11:16:38 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:17:01 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:17:01 [INFO] Response received len=1670
11:17:01 [INFO] [llm]   PXD025663_PubText.json -> 58/73 fields filled in row 0 (+32 via LLM)
11:17:01 [INFO] Written 12 rows -> /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD025663_PubText.sdrf.csv
11:17:01 [INFO] -- [5/15] PXD040582_PubText.json --
11:17:01 [INFO] [llm] Loading rules CSV from /kaggle/working/output_sdrfs/rules_0000/PXD040582_PubText.sdrf.csv
11:17:01 [INFO] Deduplicated: 24 row(s) → 1 unique N/A pattern(s)
11:17:01 [INFO] Filling 52 field(s) for group of 24 row(s)…
11:17:01 [INFO] Chars: Paper18376 = M17042+A1207+T127
11:17:01 [INFO] Tokens: Paper4592 = M4260+A301+T31
11:17:01 [INFO] Context limit 22912 Available 10965 = CT22912-MT8192-FT3755
11:17:25 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:17:46 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:17:46 [INFO] Response received len=1520
11:17:46 [INFO] [llm]   PXD040582_PubText.json -> 57/73 fields filled in row 0 (+27 via LLM)
11:17:46 [INFO] Written 24 rows -> /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD040582_PubText.sdrf.csv
11:17:46 [INFO] -- [6/15] PXD050621_PubText.json --
11:17:46 [INFO] [llm] Loading rules CSV from /kaggle/working/output_sdrfs/rules_0000/PXD050621_PubText.sdrf.csv
11:17:46 [INFO] Deduplicated: 9 row(s) → 1 unique N/A pattern(s)
11:17:46 [INFO] Filling 67 field(s) for group of 9 row(s)…
11:17:46 [INFO] Chars: Paper12512 = M10943+A1424+T145
11:17:46 [INFO] Tokens: Paper3127 = M2735+A356+T36
11:17:46 [INFO] Context limit 22912 Available 10224 = CT22912-MT8192-FT4496
11:18:29 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:18:55 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:18:55 [INFO] Response received len=2362
11:18:55 [INFO] [llm]   PXD050621_PubText.json -> 44/73 fields filled in row 0 (+29 via LLM)
11:18:55 [INFO] Written 9 rows -> /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD050621_PubText.sdrf.csv
11:18:55 [INFO] -- [7/15] PXD061009_PubText.json --
11:18:55 [INFO] [llm] Loading rules CSV from /kaggle/working/output_sdrfs/rules_0000/PXD061009_PubText.sdrf.csv
11:18:55 [INFO] Deduplicated: 2 row(s) → 1 unique N/A pattern(s)
11:18:55 [INFO] Filling 55 field(s) for group of 2 row(s)…
11:18:55 [INFO] Chars: Paper32997 = M31369+A1523+T105
11:18:55 [INFO] Tokens: Paper8248 = M7842+A380+T26
11:18:55 [INFO] Context limit 22912 Available 10803 = CT22912-MT8192-FT3917
11:19:22 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:19:49 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:19:49 [INFO] Response received len=1789
11:19:49 [INFO] [llm]   PXD061009_PubText.json -> 65/73 fields filled in row 0 (+38 via LLM)
11:19:49 [INFO] Written 2 rows -> /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD061009_PubText.sdrf.csv
11:19:49 [INFO] -- [8/15] PXD061090_PubText.json --
11:19:49 [INFO] [llm] Loading rules CSV from /kaggle/working/output_sdrfs/rules_0000/PXD061090_PubText.sdrf.csv
11:19:49 [INFO] Deduplicated: 6 row(s) → 1 unique N/A pattern(s)
11:19:49 [INFO] Filling 62 field(s) for group of 6 row(s)…
11:19:49 [INFO] Chars: Paper18053 = M16510+A1440+T103
11:19:49 [INFO] Tokens: Paper4512 = M4127+A360+T25
11:19:49 [INFO] Context limit 22912 Available 10457 = CT22912-MT8192-FT4263
11:20:15 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:20:40 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:20:40 [INFO] Response received len=1921
11:20:40 [INFO] [llm]   PXD061090_PubText.json -> 62/73 fields filled in row 0 (+42 via LLM)
11:20:40 [INFO] Written 6 rows -> /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD061090_PubText.sdrf.csv
11:20:40 [INFO] -- [9/15] PXD061136_PubText.json --
11:20:40 [INFO] [llm] Loading rules CSV from /kaggle/working/output_sdrfs/rules_0000/PXD061136_PubText.sdrf.csv
11:20:40 [INFO] Deduplicated: 2 row(s) → 1 unique N/A pattern(s)
11:20:40 [INFO] Filling 61 field(s) for group of 2 row(s)…
11:20:40 [INFO] Chars: Paper14321 = M12776+A1443+T102
11:20:40 [INFO] Tokens: Paper3579 = M3194+A360+T25
11:20:40 [INFO] Context limit 22912 Available 10545 = CT22912-MT8192-FT4175
11:21:07 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:21:30 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:21:30 [INFO] Response received len=2286
11:21:30 [INFO] [llm]   PXD061136_PubText.json -> 34/73 fields filled in row 0 (+13 via LLM)
11:21:30 [INFO] Written 2 rows -> /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD061136_PubText.sdrf.csv
11:21:30 [INFO] -- [10/15] PXD061195_PubText.json --
11:21:30 [INFO] [llm] Loading rules CSV from /kaggle/working/output_sdrfs/rules_0000/PXD061195_PubText.sdrf.csv
11:21:30 [INFO] Deduplicated: 1376 row(s) → 1 unique N/A pattern(s)
11:21:30 [INFO] Filling 51 field(s) for group of 1376 row(s)…
11:21:30 [INFO] Chars: Paper8115 = M6426+A1565+T124
11:21:30 [INFO] Tokens: Paper2028 = M1606+A391+T31
11:21:30 [INFO] Context limit 22912 Available 11007 = CT22912-MT8192-FT3713
11:21:51 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:22:09 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:22:09 [INFO] Response received len=1822
11:22:09 [INFO] [llm]   PXD061195_PubText.json -> 42/73 fields filled in row 0 (+11 via LLM)
11:22:09 [INFO] Written 1376 rows -> /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD061195_PubText.sdrf.csv
11:22:10 [INFO] -- [11/15] PXD061285_PubText.json --
11:22:10 [INFO] [llm] Loading rules CSV from /kaggle/working/output_sdrfs/rules_0000/PXD061285_PubText.sdrf.csv
11:22:10 [INFO] Deduplicated: 60 row(s) → 1 unique N/A pattern(s)
11:22:10 [INFO] Filling 57 field(s) for group of 60 row(s)…
11:22:10 [INFO] Chars: Paper32585 = M31071+A1383+T131
11:22:10 [INFO] Tokens: Paper8144 = M7767+A345+T32
11:22:10 [INFO] Context limit 22912 Available 10700 = CT22912-MT8192-FT4020
11:22:54 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:23:23 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:23:23 [INFO] Response received len=2162
11:23:23 [INFO] [llm]   PXD061285_PubText.json -> 73/73 fields filled in row 0 (+48 via LLM)
11:23:23 [INFO] Written 60 rows -> /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD061285_PubText.sdrf.csv
11:23:23 [INFO] -- [12/15] PXD062014_PubText.json --
11:23:23 [INFO] [llm] Loading rules CSV from /kaggle/working/output_sdrfs/rules_0000/PXD062014_PubText.sdrf.csv
11:23:23 [INFO] Deduplicated: 24 row(s) → 1 unique N/A pattern(s)
11:23:23 [INFO] Filling 59 field(s) for group of 24 row(s)…
11:23:23 [INFO] Chars: Paper28051 = M26655+A1300+T96
11:23:23 [INFO] Tokens: Paper7012 = M6663+A325+T24
11:23:23 [INFO] Context limit 22912 Available 10602 = CT22912-MT8192-FT4118
11:24:09 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:24:38 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:24:38 [INFO] Response received len=2121
11:24:38 [INFO] [llm]   PXD062014_PubText.json -> 41/73 fields filled in row 0 (+18 via LLM)
11:24:38 [INFO] Written 24 rows -> /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD062014_PubText.sdrf.csv
11:24:38 [INFO] -- [13/15] PXD062469_PubText.json --
11:24:38 [INFO] [llm] Loading rules CSV from /kaggle/working/output_sdrfs/rules_0000/PXD062469_PubText.sdrf.csv
11:24:38 [INFO] Deduplicated: 32 row(s) → 1 unique N/A pattern(s)
11:24:38 [INFO] Filling 56 field(s) for group of 32 row(s)…
11:24:38 [INFO] Chars: Paper15040 = M13574+A1377+T89
11:24:38 [INFO] Tokens: Paper3759 = M3393+A344+T22
11:24:38 [INFO] Context limit 22912 Available 10769 = CT22912-MT8192-FT3951
11:25:03 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:25:24 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:25:24 [INFO] Response received len=1566
11:25:24 [INFO] [llm]   PXD062469_PubText.json -> 47/73 fields filled in row 0 (+21 via LLM)
11:25:24 [INFO] Written 32 rows -> /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD062469_PubText.sdrf.csv
11:25:24 [INFO] -- [14/15] PXD062877_PubText.json --
11:25:24 [INFO] [llm] Loading rules CSV from /kaggle/working/output_sdrfs/rules_0000/PXD062877_PubText.sdrf.csv
11:25:24 [INFO] Deduplicated: 48 row(s) → 1 unique N/A pattern(s)
11:25:24 [INFO] Filling 53 field(s) for group of 48 row(s)…
11:25:24 [INFO] Chars: Paper33748 = M32232+A1422+T94
11:25:24 [INFO] Tokens: Paper8436 = M8058+A355+T23
11:25:24 [INFO] Context limit 22912 Available 10934 = CT22912-MT8192-FT3786
11:25:50 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:26:16 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:26:16 [INFO] Response received len=1715
11:26:16 [INFO] [llm]   PXD062877_PubText.json -> 70/73 fields filled in row 0 (+41 via LLM)
11:26:16 [INFO] Written 48 rows -> /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD062877_PubText.sdrf.csv
11:26:16 [INFO] -- [15/15] PXD064564_PubText.json --
11:26:16 [INFO] [llm] Loading rules CSV from /kaggle/working/output_sdrfs/rules_0000/PXD064564_PubText.sdrf.csv
11:26:16 [INFO] Deduplicated: 30 row(s) → 1 unique N/A pattern(s)
11:26:16 [INFO] Filling 59 field(s) for group of 30 row(s)…
11:26:16 [INFO] Chars: Paper17871 = M16236+A1497+T138
11:26:16 [INFO] Tokens: Paper4467 = M4059+A374+T34
11:26:16 [INFO] Context limit 22912 Available 10640 = CT22912-MT8192-FT4080
11:26:42 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:27:07 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:27:07 [INFO] Response received len=1916
11:27:07 [INFO] [llm]   PXD064564_PubText.json -> 65/73 fields filled in row 0 (+42 via LLM)
11:27:07 [INFO] Written 30 rows -> /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD064564_PubText.sdrf.csv

15/15 file(s) processed.
  LLM CSVs   -> /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/

## Next iteration(s) of LLM stage (gap filling)

In [19]:
# Preparing to run next iteration of second (LLM) stage (gap filling)
RUN=1
print((RUN, OUTPUT_DIR))

DIR_RUN2 = str(OUTPUT_DIR).replace(f"R{RUN}",f"R{(RUN+1)}")
Path(DIR_RUN2).mkdir(parents=True, exist_ok=True)
RUN+1, DIR_RUN2

(1, PosixPath('/kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1'))

(2, '/kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R2')

In [20]:
# Running next iteration of second (LLM) stage (gap filling)

!python main_fill.py --stage llm --fill-from {OUTPUT_DIR} --max-tokens {MAX_TOKENS} --context-limit {CONTEXT_LIMIT} --llm-dir "{DIR_RUN2}"  --model {LLM_MODEL} --base-url {api_base} --api-key {api_key} --pattern PXD*.json "{TEST_TEXT_DIR}"

11:27:08 [INFO] Pattern 'PXD*.json' in /kaggle/input/competitions/harmonizing-the-data-of-your-data/Test PubText/Test PubText -> 15 file(s)
11:27:08 [INFO] -- [1/15] PXD004010_PubText.json --
11:27:08 [INFO] [llm] Loading rules CSV from /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD004010_PubText.sdrf.csv
11:27:15 [INFO] Deduplicated: 10 row(s) → 1 unique N/A pattern(s)
11:27:15 [INFO] Filling 37 field(s) for group of 10 row(s)…
11:27:15 [INFO] Chars: Paper9630 = M8027+A1493+T110
11:27:15 [INFO] Tokens: Paper2406 = M2006+A373+T27
11:27:15 [INFO] Context limit 22912 Available 11646 = CT22912-MT8192-FT3074
11:27:28 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:27:44 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:27:44 [INFO] Response received len=1347
11:27:44 [INFO] [llm]   PXD004010_PubText.json -> 58/73 fields filled in row 0 (+13 via LLM)
11:27:44 [INFO] Written 10 rows -> /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R2/PXD004010_PubText.sdrf.csv
11:27:44 [INFO] -- [2/15] PXD016436_PubText.json --
11:27:44 [INFO] [llm] Loading rules CSV from /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD016436_PubText.sdrf.csv
11:27:44 [INFO] Deduplicated: 18 row(s) → 1 unique N/A pattern(s)
11:27:44 [INFO] Filling 38 field(s) for group of 18 row(s)…
11:27:44 [INFO] Chars: Paper6853 = M6201+A577+T75
11:27:44 [INFO] Tokens: Paper1712 = M1550+A144+T18
11:27:44 [INFO] Context limit 22912 Available 11630 = CT22912-MT8192-FT3090
11:28:00 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:28:15 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:28:15 [INFO] Response received len=1335
11:28:15 [INFO] [llm]   PXD016436_PubText.json -> 53/73 fields filled in row 0 (+9 via LLM)
11:28:15 [INFO] Written 18 rows -> /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R2/PXD016436_PubText.sdrf.csv
11:28:15 [INFO] -- [3/15] PXD019519_PubText.json --
11:28:15 [INFO] [llm] Loading rules CSV from /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD019519_PubText.sdrf.csv
11:28:15 [INFO] Deduplicated: 6 row(s) → 1 unique N/A pattern(s)
11:28:15 [INFO] Filling 21 field(s) for group of 6 row(s)…
11:28:15 [INFO] Chars: Paper43567 = M42096+A1394+T77
11:28:15 [INFO] Tokens: Paper10891 = M10524+A348+T19
11:28:15 [INFO] Context limit 22912 Available 12290 = CT22912-MT8192-FT2430
11:28:43 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:29:13 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:29:13 [INFO] Response received len=768
11:29:13 [INFO] [llm]   PXD019519_PubText.json -> 66/73 fields filled in row 0 (+5 via LLM)
11:29:13 [INFO] Written 6 rows -> /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R2/PXD019519_PubText.sdrf.csv
11:29:13 [INFO] -- [4/15] PXD025663_PubText.json --
11:29:13 [INFO] [llm] Loading rules CSV from /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD025663_PubText.sdrf.csv
11:29:13 [INFO] Deduplicated: 12 row(s) → 1 unique N/A pattern(s)
11:29:13 [INFO] Filling 24 field(s) for group of 12 row(s)…
11:29:13 [INFO] Chars: Paper18589 = M16465+A2069+T55
11:29:13 [INFO] Tokens: Paper4646 = M4116+A517+T13
11:29:13 [INFO] Context limit 22912 Available 12210 = CT22912-MT8192-FT2510
11:29:30 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:29:44 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:29:44 [INFO] Response received len=818
11:29:44 [INFO] [llm]   PXD025663_PubText.json -> 67/73 fields filled in row 0 (+9 via LLM)
11:29:44 [INFO] Written 12 rows -> /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R2/PXD025663_PubText.sdrf.csv
11:29:44 [INFO] -- [5/15] PXD040582_PubText.json --
11:29:44 [INFO] [llm] Loading rules CSV from /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD040582_PubText.sdrf.csv
11:29:44 [INFO] Deduplicated: 24 row(s) → 1 unique N/A pattern(s)
11:29:44 [INFO] Filling 25 field(s) for group of 24 row(s)…
11:29:44 [INFO] Chars: Paper18376 = M17042+A1207+T127
11:29:44 [INFO] Tokens: Paper4592 = M4260+A301+T31
11:29:44 [INFO] Context limit 22912 Available 12150 = CT22912-MT8192-FT2570
11:30:01 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:30:17 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:30:17 [INFO] Response received len=1006
11:30:17 [INFO] [llm]   PXD040582_PubText.json -> 66/73 fields filled in row 0 (+9 via LLM)
11:30:17 [INFO] Written 24 rows -> /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R2/PXD040582_PubText.sdrf.csv
11:30:17 [INFO] -- [6/15] PXD050621_PubText.json --
11:30:17 [INFO] [llm] Loading rules CSV from /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD050621_PubText.sdrf.csv
11:30:17 [INFO] Deduplicated: 9 row(s) → 1 unique N/A pattern(s)
11:30:17 [INFO] Filling 38 field(s) for group of 9 row(s)…
11:30:17 [INFO] Chars: Paper12512 = M10943+A1424+T145
11:30:17 [INFO] Tokens: Paper3127 = M2735+A356+T36
11:30:17 [INFO] Context limit 22912 Available 11593 = CT22912-MT8192-FT3127
11:30:35 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:30:52 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:30:52 [INFO] Response received len=1240
11:30:52 [INFO] [llm]   PXD050621_PubText.json -> 55/73 fields filled in row 0 (+11 via LLM)
11:30:52 [INFO] Written 9 rows -> /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R2/PXD050621_PubText.sdrf.csv
11:30:52 [INFO] -- [7/15] PXD061009_PubText.json --
11:30:52 [INFO] [llm] Loading rules CSV from /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD061009_PubText.sdrf.csv
11:30:52 [INFO] Deduplicated: 2 row(s) → 1 unique N/A pattern(s)
11:30:52 [INFO] Filling 17 field(s) for group of 2 row(s)…
11:30:52 [INFO] Chars: Paper32997 = M31369+A1523+T105
11:30:52 [INFO] Tokens: Paper8248 = M7842+A380+T26
11:30:52 [INFO] Context limit 22912 Available 12459 = CT22912-MT8192-FT2261
11:31:09 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:31:25 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:31:25 [INFO] Response received len=540
11:31:25 [INFO] [llm]   PXD061009_PubText.json -> 66/73 fields filled in row 0 (+1 via LLM)
11:31:25 [INFO] Written 2 rows -> /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R2/PXD061009_PubText.sdrf.csv
11:31:25 [INFO] -- [8/15] PXD061090_PubText.json --
11:31:25 [INFO] [llm] Loading rules CSV from /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD061090_PubText.sdrf.csv
11:31:25 [INFO] Deduplicated: 6 row(s) → 1 unique N/A pattern(s)
11:31:25 [INFO] Filling 20 field(s) for group of 6 row(s)…
11:31:25 [INFO] Chars: Paper18053 = M16510+A1440+T103
11:31:25 [INFO] Tokens: Paper4512 = M4127+A360+T25
11:31:25 [INFO] Context limit 22912 Available 12375 = CT22912-MT8192-FT2345
11:31:39 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:31:52 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:31:52 [INFO] Response received len=694
11:31:52 [INFO] [llm]   PXD061090_PubText.json -> 69/73 fields filled in row 0 (+7 via LLM)
11:31:52 [INFO] Written 6 rows -> /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R2/PXD061090_PubText.sdrf.csv
11:31:52 [INFO] -- [9/15] PXD061136_PubText.json --
11:31:52 [INFO] [llm] Loading rules CSV from /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD061136_PubText.sdrf.csv
11:31:52 [INFO] Deduplicated: 2 row(s) → 1 unique N/A pattern(s)
11:31:52 [INFO] Filling 48 field(s) for group of 2 row(s)…
11:31:52 [INFO] Chars: Paper14321 = M12776+A1443+T102
11:31:52 [INFO] Tokens: Paper3579 = M3194+A360+T25
11:31:52 [INFO] Context limit 22912 Available 11108 = CT22912-MT8192-FT3612
11:32:14 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:32:33 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:32:33 [INFO] Response received len=1403
11:32:33 [INFO] [llm]   PXD061136_PubText.json -> 50/73 fields filled in row 0 (+16 via LLM)
11:32:33 [INFO] Written 2 rows -> /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R2/PXD061136_PubText.sdrf.csv
11:32:33 [INFO] -- [10/15] PXD061195_PubText.json --
11:32:33 [INFO] [llm] Loading rules CSV from /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD061195_PubText.sdrf.csv
11:32:33 [INFO] Deduplicated: 1376 row(s) → 1 unique N/A pattern(s)
11:32:33 [INFO] Filling 40 field(s) for group of 1376 row(s)…
11:32:33 [INFO] Chars: Paper8115 = M6426+A1565+T124
11:32:33 [INFO] Tokens: Paper2028 = M1606+A391+T31
11:32:33 [INFO] Context limit 22912 Available 11530 = CT22912-MT8192-FT3190
11:32:50 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:33:06 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:33:06 [INFO] Response received len=1195
11:33:06 [INFO] [llm]   PXD061195_PubText.json -> 58/73 fields filled in row 0 (+16 via LLM)
11:33:06 [INFO] Written 1376 rows -> /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R2/PXD061195_PubText.sdrf.csv
11:33:06 [INFO] -- [11/15] PXD061285_PubText.json --
11:33:06 [INFO] [llm] Loading rules CSV from /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD061285_PubText.sdrf.csv
11:33:06 [INFO] Deduplicated: 60 row(s) → 1 unique N/A pattern(s)
11:33:06 [INFO] Filling 9 field(s) for group of 60 row(s)…
11:33:06 [INFO] Chars: Paper32585 = M31071+A1383+T131
11:33:06 [INFO] Tokens: Paper8144 = M7767+A345+T32
11:33:06 [INFO] Context limit 22912 Available 12747 = CT22912-MT8192-FT1973
11:33:21 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:33:36 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:33:36 [INFO] Response received len=327
11:33:36 [INFO] [llm]   PXD061285_PubText.json -> 73/73 fields filled in row 0 (+0 via LLM)
11:33:36 [INFO] Written 60 rows -> /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R2/PXD061285_PubText.sdrf.csv
11:33:36 [INFO] -- [12/15] PXD062014_PubText.json --
11:33:36 [INFO] [llm] Loading rules CSV from /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD062014_PubText.sdrf.csv
11:33:36 [INFO] Deduplicated: 24 row(s) → 1 unique N/A pattern(s)
11:33:36 [INFO] Filling 41 field(s) for group of 24 row(s)…
11:33:36 [INFO] Chars: Paper28051 = M26655+A1300+T96
11:33:36 [INFO] Tokens: Paper7012 = M6663+A325+T24
11:33:36 [INFO] Context limit 22912 Available 11444 = CT22912-MT8192-FT3276
11:33:59 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:34:22 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:34:22 [INFO] Response received len=1367
11:34:22 [INFO] [llm]   PXD062014_PubText.json -> 58/73 fields filled in row 0 (+17 via LLM)
11:34:22 [INFO] Written 24 rows -> /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R2/PXD062014_PubText.sdrf.csv
11:34:22 [INFO] -- [13/15] PXD062469_PubText.json --
11:34:22 [INFO] [llm] Loading rules CSV from /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD062469_PubText.sdrf.csv
11:34:22 [INFO] Deduplicated: 32 row(s) → 1 unique N/A pattern(s)
11:34:22 [INFO] Filling 35 field(s) for group of 32 row(s)…
11:34:22 [INFO] Chars: Paper15040 = M13574+A1377+T89
11:34:22 [INFO] Tokens: Paper3759 = M3393+A344+T22
11:34:22 [INFO] Context limit 22912 Available 11715 = CT22912-MT8192-FT3005
11:34:37 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:34:53 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:34:53 [INFO] Response received len=1016
11:34:53 [INFO] [llm]   PXD062469_PubText.json -> 57/73 fields filled in row 0 (+10 via LLM)
11:34:53 [INFO] Written 32 rows -> /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R2/PXD062469_PubText.sdrf.csv
11:34:53 [INFO] -- [14/15] PXD062877_PubText.json --
11:34:53 [INFO] [llm] Loading rules CSV from /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD062877_PubText.sdrf.csv
11:34:53 [INFO] Deduplicated: 48 row(s) → 1 unique N/A pattern(s)
11:34:53 [INFO] Filling 12 field(s) for group of 48 row(s)…
11:34:53 [INFO] Chars: Paper33748 = M32232+A1422+T94
11:34:53 [INFO] Tokens: Paper8436 = M8058+A355+T23
11:34:53 [INFO] Context limit 22912 Available 12613 = CT22912-MT8192-FT2107
11:35:09 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:35:24 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:35:24 [INFO] Response received len=478
11:35:24 [INFO] [llm]   PXD062877_PubText.json -> 73/73 fields filled in row 0 (+3 via LLM)
11:35:24 [INFO] Written 48 rows -> /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R2/PXD062877_PubText.sdrf.csv
11:35:24 [INFO] -- [15/15] PXD064564_PubText.json --
11:35:24 [INFO] [llm] Loading rules CSV from /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD064564_PubText.sdrf.csv
11:35:24 [INFO] Deduplicated: 30 row(s) → 1 unique N/A pattern(s)
11:35:24 [INFO] Filling 17 field(s) for group of 30 row(s)…
11:35:24 [INFO] Chars: Paper17871 = M16236+A1497+T138
11:35:24 [INFO] Tokens: Paper4467 = M4059+A374+T34
11:35:24 [INFO] Context limit 22912 Available 12460 = CT22912-MT8192-FT2260
11:35:38 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:35:50 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:35:50 [INFO] Response received len=517
11:35:50 [INFO] [llm]   PXD064564_PubText.json -> 70/73 fields filled in row 0 (+5 via LLM)
11:35:50 [INFO] Written 30 rows -> /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R2/PXD064564_PubText.sdrf.csv

15/15 file(s) processed.
  LLM CSVs   -> /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R2/

In [21]:
# Preparing to run next iteration of second (LLM) stage (gap filling)

DIR_RUN3 = str(OUTPUT_DIR).replace(f"R{RUN}",f"R{(RUN+2)}")
Path(DIR_RUN3).mkdir(parents=True, exist_ok=True)
RUN+2, DIR_RUN3

(3, '/kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R3')

In [22]:
# Running next iteration of second (LLM) stage (gap filling) 

!python main_fill.py --stage llm --fill-from {DIR_RUN2} --max-tokens {MAX_TOKENS} --context-limit {CONTEXT_LIMIT} --llm-dir "{DIR_RUN3}"  --model {LLM_MODEL} --base-url {api_base} --api-key {api_key} --pattern PXD*.json "{TEST_TEXT_DIR}"

11:35:51 [INFO] Pattern 'PXD*.json' in /kaggle/input/competitions/harmonizing-the-data-of-your-data/Test PubText/Test PubText -> 15 file(s)
11:35:51 [INFO] -- [1/15] PXD004010_PubText.json --
11:35:51 [INFO] [llm] Loading rules CSV from /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R2/PXD004010_PubText.sdrf.csv
11:35:58 [INFO] Deduplicated: 10 row(s) → 1 unique N/A pattern(s)
11:35:58 [INFO] Filling 24 field(s) for group of 10 row(s)…
11:35:58 [INFO] Chars: Paper9630 = M8027+A1493+T110
11:35:58 [INFO] Tokens: Paper2406 = M2006+A373+T27
11:35:58 [INFO] Context limit 22912 Available 12195 = CT22912-MT8192-FT2525
11:36:11 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:36:20 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:36:20 [INFO] Response received len=487
11:36:20 [INFO] [llm]   PXD004010_PubText.json -> 59/73 fields filled in row 0 (+1 via LLM)
11:36:20 [INFO] Written 10 rows -> /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R3/PXD004010_PubText.sdrf.csv
11:36:20 [INFO] -- [2/15] PXD016436_PubText.json --
11:36:20 [INFO] [llm] Loading rules CSV from /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R2/PXD016436_PubText.sdrf.csv
11:36:20 [INFO] Deduplicated: 18 row(s) → 1 unique N/A pattern(s)
11:36:20 [INFO] Filling 29 field(s) for group of 18 row(s)…
11:36:20 [INFO] Chars: Paper6853 = M6201+A577+T75
11:36:20 [INFO] Tokens: Paper1712 = M1550+A144+T18
11:36:20 [INFO] Context limit 22912 Available 11987 = CT22912-MT8192-FT2733
11:36:33 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:36:46 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:36:46 [INFO] Response received len=1027
11:36:46 [INFO] [llm]   PXD016436_PubText.json -> 58/73 fields filled in row 0 (+5 via LLM)
11:36:46 [INFO] Written 18 rows -> /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R3/PXD016436_PubText.sdrf.csv
11:36:46 [INFO] -- [3/15] PXD019519_PubText.json --
11:36:46 [INFO] [llm] Loading rules CSV from /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R2/PXD019519_PubText.sdrf.csv
11:36:46 [INFO] Deduplicated: 6 row(s) → 1 unique N/A pattern(s)
11:36:46 [INFO] Filling 16 field(s) for group of 6 row(s)…
11:36:46 [INFO] Chars: Paper43567 = M42096+A1394+T77
11:36:46 [INFO] Tokens: Paper10891 = M10524+A348+T19
11:36:46 [INFO] Context limit 22912 Available 12507 = CT22912-MT8192-FT2213
11:37:15 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:37:43 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:37:43 [INFO] Response received len=727
11:37:43 [INFO] [llm]   PXD019519_PubText.json -> 67/73 fields filled in row 0 (+1 via LLM)
11:37:43 [INFO] Written 6 rows -> /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R3/PXD019519_PubText.sdrf.csv
11:37:43 [INFO] -- [4/15] PXD025663_PubText.json --
11:37:43 [INFO] [llm] Loading rules CSV from /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R2/PXD025663_PubText.sdrf.csv
11:37:43 [INFO] Deduplicated: 12 row(s) → 1 unique N/A pattern(s)
11:37:43 [INFO] Filling 15 field(s) for group of 12 row(s)…
11:37:43 [INFO] Chars: Paper18589 = M16465+A2069+T55
11:37:43 [INFO] Tokens: Paper4646 = M4116+A517+T13
11:37:43 [INFO] Context limit 22912 Available 12562 = CT22912-MT8192-FT2158
11:37:58 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:38:10 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:38:10 [INFO] Response received len=563
11:38:10 [INFO] [llm]   PXD025663_PubText.json -> 68/73 fields filled in row 0 (+1 via LLM)
11:38:10 [INFO] Written 12 rows -> /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R3/PXD025663_PubText.sdrf.csv
11:38:10 [INFO] -- [5/15] PXD040582_PubText.json --
11:38:10 [INFO] [llm] Loading rules CSV from /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R2/PXD040582_PubText.sdrf.csv
11:38:10 [INFO] Deduplicated: 24 row(s) → 1 unique N/A pattern(s)
11:38:10 [INFO] Filling 16 field(s) for group of 24 row(s)…
11:38:10 [INFO] Chars: Paper18376 = M17042+A1207+T127
11:38:10 [INFO] Tokens: Paper4592 = M4260+A301+T31
11:38:10 [INFO] Context limit 22912 Available 12507 = CT22912-MT8192-FT2213
11:38:24 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:38:36 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:38:36 [INFO] Response received len=578
11:38:36 [INFO] [llm]   PXD040582_PubText.json -> 67/73 fields filled in row 0 (+1 via LLM)
11:38:36 [INFO] Written 24 rows -> /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R3/PXD040582_PubText.sdrf.csv
11:38:36 [INFO] -- [6/15] PXD050621_PubText.json --
11:38:36 [INFO] [llm] Loading rules CSV from /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R2/PXD050621_PubText.sdrf.csv
11:38:36 [INFO] Deduplicated: 9 row(s) → 1 unique N/A pattern(s)
11:38:36 [INFO] Filling 27 field(s) for group of 9 row(s)…
11:38:36 [INFO] Chars: Paper12512 = M10943+A1424+T145
11:38:36 [INFO] Tokens: Paper3127 = M2735+A356+T36
11:38:36 [INFO] Context limit 22912 Available 12017 = CT22912-MT8192-FT2703
11:38:49 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:39:02 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:39:02 [INFO] Response received len=962
11:39:02 [INFO] [llm]   PXD050621_PubText.json -> 60/73 fields filled in row 0 (+5 via LLM)
11:39:02 [INFO] Written 9 rows -> /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R3/PXD050621_PubText.sdrf.csv
11:39:02 [INFO] -- [7/15] PXD061009_PubText.json --
11:39:02 [INFO] [llm] Loading rules CSV from /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R2/PXD061009_PubText.sdrf.csv
11:39:02 [INFO] Deduplicated: 2 row(s) → 1 unique N/A pattern(s)
11:39:02 [INFO] Filling 16 field(s) for group of 2 row(s)…
11:39:02 [INFO] Chars: Paper32997 = M31369+A1523+T105
11:39:02 [INFO] Tokens: Paper8248 = M7842+A380+T26
11:39:02 [INFO] Context limit 22912 Available 12509 = CT22912-MT8192-FT2211
11:39:19 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:39:33 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:39:33 [INFO] Response received len=287
11:39:33 [INFO] [llm]   PXD061009_PubText.json -> 66/73 fields filled in row 0 (+0 via LLM)
11:39:33 [INFO] Written 2 rows -> /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R3/PXD061009_PubText.sdrf.csv
11:39:33 [INFO] -- [8/15] PXD061090_PubText.json --
11:39:33 [INFO] [llm] Loading rules CSV from /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R2/PXD061090_PubText.sdrf.csv
11:39:33 [INFO] Deduplicated: 6 row(s) → 1 unique N/A pattern(s)
11:39:33 [INFO] Filling 13 field(s) for group of 6 row(s)…
11:39:33 [INFO] Chars: Paper18053 = M16510+A1440+T103
11:39:33 [INFO] Tokens: Paper4512 = M4127+A360+T25
11:39:33 [INFO] Context limit 22912 Available 12638 = CT22912-MT8192-FT2082
11:39:45 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:39:55 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:39:55 [INFO] Response received len=320
11:39:55 [INFO] [llm]   PXD061090_PubText.json -> 69/73 fields filled in row 0 (+0 via LLM)
11:39:55 [INFO] Written 6 rows -> /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R3/PXD061090_PubText.sdrf.csv
11:39:55 [INFO] -- [9/15] PXD061136_PubText.json --
11:39:55 [INFO] [llm] Loading rules CSV from /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R2/PXD061136_PubText.sdrf.csv
11:39:55 [INFO] Deduplicated: 2 row(s) → 1 unique N/A pattern(s)
11:39:55 [INFO] Filling 32 field(s) for group of 2 row(s)…
11:39:55 [INFO] Chars: Paper14321 = M12776+A1443+T102
11:39:55 [INFO] Tokens: Paper3579 = M3194+A360+T25
11:39:55 [INFO] Context limit 22912 Available 11854 = CT22912-MT8192-FT2866
11:40:11 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:40:26 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:40:26 [INFO] Response received len=1084
11:40:26 [INFO] [llm]   PXD061136_PubText.json -> 56/73 fields filled in row 0 (+6 via LLM)
11:40:26 [INFO] Written 2 rows -> /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R3/PXD061136_PubText.sdrf.csv
11:40:26 [INFO] -- [10/15] PXD061195_PubText.json --
11:40:26 [INFO] [llm] Loading rules CSV from /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R2/PXD061195_PubText.sdrf.csv
11:40:26 [INFO] Deduplicated: 1376 row(s) → 1 unique N/A pattern(s)
11:40:26 [INFO] Filling 24 field(s) for group of 1376 row(s)…
11:40:26 [INFO] Chars: Paper8115 = M6426+A1565+T124
11:40:26 [INFO] Tokens: Paper2028 = M1606+A391+T31
11:40:26 [INFO] Context limit 22912 Available 12197 = CT22912-MT8192-FT2523
11:40:38 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:40:49 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:40:49 [INFO] Response received len=689
11:40:49 [INFO] [llm]   PXD061195_PubText.json -> 58/73 fields filled in row 0 (+0 via LLM)
11:40:49 [INFO] Written 1376 rows -> /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R3/PXD061195_PubText.sdrf.csv
11:40:49 [INFO] -- [11/15] PXD061285_PubText.json --
11:40:49 [INFO] [llm] Loading rules CSV from /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R2/PXD061285_PubText.sdrf.csv
11:40:49 [INFO] Deduplicated: 60 row(s) → 1 unique N/A pattern(s)
11:40:49 [INFO] Filling 9 field(s) for group of 60 row(s)…
11:40:49 [INFO] Chars: Paper32585 = M31071+A1383+T131
11:40:49 [INFO] Tokens: Paper8144 = M7767+A345+T32
11:40:49 [INFO] Context limit 22912 Available 12747 = CT22912-MT8192-FT1973
11:41:05 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:41:20 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:41:20 [INFO] Response received len=327
11:41:20 [INFO] [llm]   PXD061285_PubText.json -> 73/73 fields filled in row 0 (+0 via LLM)
11:41:20 [INFO] Written 60 rows -> /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R3/PXD061285_PubText.sdrf.csv
11:41:20 [INFO] -- [12/15] PXD062014_PubText.json --
11:41:20 [INFO] [llm] Loading rules CSV from /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R2/PXD062014_PubText.sdrf.csv
11:41:20 [INFO] Deduplicated: 24 row(s) → 1 unique N/A pattern(s)
11:41:20 [INFO] Filling 24 field(s) for group of 24 row(s)…
11:41:20 [INFO] Chars: Paper28051 = M26655+A1300+T96
11:41:20 [INFO] Tokens: Paper7012 = M6663+A325+T24
11:41:20 [INFO] Context limit 22912 Available 12174 = CT22912-MT8192-FT2546
11:41:39 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:41:57 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:41:57 [INFO] Response received len=563
11:41:57 [INFO] [llm]   PXD062014_PubText.json -> 66/73 fields filled in row 0 (+8 via LLM)
11:41:57 [INFO] Written 24 rows -> /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R3/PXD062014_PubText.sdrf.csv
11:41:57 [INFO] -- [13/15] PXD062469_PubText.json --
11:41:57 [INFO] [llm] Loading rules CSV from /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R2/PXD062469_PubText.sdrf.csv
11:41:57 [INFO] Deduplicated: 32 row(s) → 1 unique N/A pattern(s)
11:41:57 [INFO] Filling 25 field(s) for group of 32 row(s)…
11:41:57 [INFO] Chars: Paper15040 = M13574+A1377+T89
11:41:57 [INFO] Tokens: Paper3759 = M3393+A344+T22
11:41:57 [INFO] Context limit 22912 Available 12185 = CT22912-MT8192-FT2535
11:42:13 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:42:27 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:42:27 [INFO] Response received len=753
11:42:27 [INFO] [llm]   PXD062469_PubText.json -> 62/73 fields filled in row 0 (+5 via LLM)
11:42:27 [INFO] Written 32 rows -> /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R3/PXD062469_PubText.sdrf.csv
11:42:27 [INFO] -- [14/15] PXD062877_PubText.json --
11:42:27 [INFO] [llm] Loading rules CSV from /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R2/PXD062877_PubText.sdrf.csv
11:42:27 [INFO] Deduplicated: 48 row(s) → 1 unique N/A pattern(s)
11:42:27 [INFO] Filling 9 field(s) for group of 48 row(s)…
11:42:27 [INFO] Chars: Paper33748 = M32232+A1422+T94
11:42:27 [INFO] Tokens: Paper8436 = M8058+A355+T23
11:42:27 [INFO] Context limit 22912 Available 12747 = CT22912-MT8192-FT1973
11:42:43 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:42:58 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:42:58 [INFO] Response received len=351
11:42:58 [INFO] [llm]   PXD062877_PubText.json -> 73/73 fields filled in row 0 (+0 via LLM)
11:42:58 [INFO] Written 48 rows -> /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R3/PXD062877_PubText.sdrf.csv
11:42:58 [INFO] -- [15/15] PXD064564_PubText.json --
11:42:58 [INFO] [llm] Loading rules CSV from /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R2/PXD064564_PubText.sdrf.csv
11:42:58 [INFO] Deduplicated: 30 row(s) → 1 unique N/A pattern(s)
11:42:58 [INFO] Filling 12 field(s) for group of 30 row(s)…
11:42:58 [INFO] Chars: Paper17871 = M16236+A1497+T138
11:42:58 [INFO] Tokens: Paper4467 = M4059+A374+T34
11:42:58 [INFO] Context limit 22912 Available 12669 = CT22912-MT8192-FT2051
11:43:10 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:43:21 [INFO] HTTP Request: POST http://127.0.0.1:8080/v1/chat/completions "HTTP/1.1 200 OK"
11:43:21 [INFO] Response received len=431
11:43:21 [INFO] [llm]   PXD064564_PubText.json -> 73/73 fields filled in row 0 (+3 via LLM)
11:43:21 [INFO] Written 30 rows -> /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R3/PXD064564_PubText.sdrf.csv

15/15 file(s) processed.
  LLM CSVs   -> /kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R3/

### Any improvements over the iterative runs ?

In [23]:
import pandas as pd
from src.eval import score, dataframe_diff, print_column_value_diffs

pxds = pd.read_csv(SAMPLE_SUB)["PXD"].unique()
for pxd in pxds:
    run1 = pd.read_csv(Path(DIR_RUN2) / f"{pxd}_PubText.sdrf.csv")
    run1["PXD"] = pxd
    run2 = pd.read_csv(Path(DIR_RUN3) / f"{pxd}_PubText.sdrf.csv")
    run2["PXD"] = pxd

    f1, harm_norm, harm_subm, eval_df = score(run1, run2, row_id_column_name="ID")
    print(f"## {pxd} F1={f1}")
    display(eval_df.loc[eval_df["f1"]<0.8].head())
    
    diff = dataframe_diff(run1, run2)
    if diff.shape[0] > 0:
        #diff.to_csv(str(SUBMISSION).replace(".csv", "_normalized_diff.csv"), index=False)
        print(f"## {pxd} Column differences")
        print_column_value_diffs(diff)

## PXD004010 F1=0.9861111111111112

          pxd         AnnotationType  precision  recall   f1  jacc
34  PXD004010  Comment[GradientTime]        0.0     0.0  0.0   0.0

## PXD004010 Column differences

Column: Comment[GradientTime]
not applicable → 90 min
## PXD050621 F1=0.9305555555555556

          pxd                   AnnotationType  precision  recall   f1  jacc
34  PXD050621            Comment[GradientTime]        0.0     0.0  0.0   0.0
35  PXD050621        Comment[EnrichmentMethod]        0.0     0.0  0.0   0.0
40  PXD050621  Comment[PrecursorMassTolerance]        0.0     0.0  0.0   0.0
45  PXD050621      Characteristics[GrowthRate]        0.0     0.0  0.0   0.0
62  PXD050621    Characteristics[PooledSample]        0.0     0.0  0.0   0.0

## PXD050621 Column differences

Column: Characteristics[GrowthRate]
not applicable → exponential phase

Column: Characteristics[PooledSample]
not applicable → no

Column: Comment[EnrichmentMethod]
not applicable → IMAC

Column: Comment[GradientTime]
not applicable → 90 min

Column: Comment[PrecursorMassTolerance]
not applicable → 10 ppm
## PXD062014 F1=0.8948412698412699

          pxd                     AnnotationType  precision  recall   f1  jacc
24  PXD062014               Characteristics[Age]        0.0     0.0  0.0   0.0
26  PXD062014  Characteristics[AncestryCategory]        0.0     0.0  0.0   0.0
35  PXD062014          Comment[EnrichmentMethod]        0.0     0.0  0.0   0.0
38  PXD062014               Characteristics[BMI]        0.0     0.0  0.0   0.0
45  PXD062014        Characteristics[GrowthRate]        0.0     0.0  0.0   0.0

## PXD062014 Column differences

Column: Characteristics[Age]
not applicable → 45 years

Column: Characteristics[AncestryCategory]
not applicable → European

Column: Characteristics[BMI]
not applicable → 22.5

Column: Characteristics[Depletion]
not applicable → MARS14 depletion

Column: Characteristics[Genotype]
not applicable → wild-type

Column: Characteristics[GrowthRate]
not applicable → exponential phase

Column: Characteristics[Modification].3
not applicable → Deamidation (NQ)

Column: Comment[EnrichmentMethod]
not applicable → IMAC
## PXD061136 F1=0.9351851851851851

,pxd,AnnotationType,precision,recall,f1,jacc
10,PXD061136,Comment[NumberOfMissedCleavages],0.00,0.0,0.000000,0.0
34,PXD061136,Comment[GradientTime],0.00,0.0,0.000000,0.0
40,PXD061136,Comment[PrecursorMassTolerance],0.00,0.0,0.000000,0.0
61,PXD061136,Characteristics[Modification],0.25,0.5,0.333333,0.5
68,PXD061136,Characteristics[NumberOfBiologicalReplicates],0.00,0.0,0.000000,0.0

## PXD061136 Column differences

Column: Characteristics[Modification].2
not applicable → Acetyl (N-term)

Column: Characteristics[Modification].3
not applicable → Deamidation (NQ)

Column: Characteristics[NumberOfBiologicalReplicates]
not applicable → 3

Column: Comment[GradientTime]
not applicable → 90 min

Column: Comment[NumberOfMissedCleavages]
not applicable → 2

Column: Comment[PrecursorMassTolerance]
not applicable → 10 ppm
## PXD016436 F1=0.9367283950617283

,pxd,AnnotationType,precision,recall,f1,jacc
3,PXD016436,Characteristics[Staining],0.0,0.0,0.000000,0.0
8,PXD016436,Characteristics[GeneticModification],0.0,0.0,0.000000,0.0
23,PXD016436,Comment[CollisionEnergy],0.0,0.0,0.000000,0.0
61,PXD016436,Characteristics[Modification],0.4,0.5,0.444444,0.8
64,PXD016436,Characteristics[Genotype],0.0,0.0,0.000000,0.0

## PXD016436 Column differences

Column: Characteristics[GeneticModification]
not applicable → BRCA1 knockout

Column: Characteristics[Genotype]
not applicable → wild-type

Column: Characteristics[Modification].3
not applicable → Deamidation (NQ)

Column: Characteristics[Staining]
not applicable → Coomassie

Column: Comment[CollisionEnergy]
not applicable → 28 NCE
## PXD062877 F1=1.0

Empty DataFrame
Columns: [pxd, AnnotationType, precision, recall, f1, jacc]
Index: []

## PXD064564 F1=0.9907407407407407

,pxd,AnnotationType,precision,recall,f1,jacc
61,PXD064564,Characteristics[Modification],0.285714,0.4,0.333333,0.5

## PXD064564 Column differences

Column: Characteristics[Modification].4
not applicable → Phosphorylation

Column: Characteristics[Modification].5
not applicable → Ubiquitination

Column: Characteristics[Modification].6
not applicable → SUMOylation
## PXD062469 F1=0.9367283950617283

,pxd,AnnotationType,precision,recall,f1,jacc
7,PXD062469,Characteristics[SpikedCompound],0.0,0.0,0.000000,0.0
8,PXD062469,Characteristics[GeneticModification],0.0,0.0,0.000000,0.0
29,PXD062469,Characteristics[SamplingTime],0.0,0.0,0.000000,0.0
61,PXD062469,Characteristics[Modification],0.4,0.5,0.444444,0.8
64,PXD062469,Characteristics[Genotype],0.0,0.0,0.000000,0.0

## PXD062469 Column differences

Column: Characteristics[GeneticModification]
not applicable → BRCA1 knockout;TP53 siRNA knockdown

Column: Characteristics[Genotype]
not applicable → wild-type;p53-/-;APP/PS1

Column: Characteristics[Modification].3
not applicable → Deamidation (NQ)

Column: Characteristics[SamplingTime]
not applicable → 0 h;24 h;day 7

Column: Characteristics[SpikedCompound]
not applicable → iRT peptides
## PXD061009 F1=1.0

Empty DataFrame
Columns: [pxd, AnnotationType, precision, recall, f1, jacc]
Index: []

## PXD061195 F1=1.0

Empty DataFrame
Columns: [pxd, AnnotationType, precision, recall, f1, jacc]
Index: []

## PXD061090 F1=1.0

Empty DataFrame
Columns: [pxd, AnnotationType, precision, recall, f1, jacc]
Index: []

## PXD040582 F1=0.9861111111111112

          pxd              AnnotationType  precision  recall   f1  jacc
67  PXD040582  Characteristics[Depletion]        0.0     0.0  0.0   0.0

## PXD040582 Column differences

Column: Characteristics[Depletion]
not applicable → MARS14 depletion
## PXD025663 F1=0.9861111111111112

          pxd               AnnotationType  precision  recall   f1  jacc
45  PXD025663  Characteristics[GrowthRate]        0.0     0.0  0.0   0.0

## PXD025663 Column differences

Column: Characteristics[GrowthRate]
not applicable → exponential phase
## PXD019519 F1=0.9861111111111112

          pxd              AnnotationType  precision  recall   f1  jacc
67  PXD019519  Characteristics[Depletion]        0.0     0.0  0.0   0.0

## PXD019519 Column differences

Column: Characteristics[Depletion]
not applicable → NQO1-activatable compound causes an irreversible collapse of the UPS, accompanied by a general accumulation of ubiquitylated proteins
## PXD061285 F1=1.0

Empty DataFrame
Columns: [pxd, AnnotationType, precision, recall, f1, jacc]
Index: []

## Combine into submission

In [24]:
RUN=1
SDRF_FILES_OUTPUT = OUTPUT_DIR

RUN=2
SDRF_FILES_OUTPUT=DIR_RUN2

RUN=3
SDRF_FILES_OUTPUT=DIR_RUN3

In [25]:
# --- CONFIG ---
output_folder = Path(SDRF_FILES_OUTPUT)  # folder with all SDRF CSVs
sample_csv = Path(SAMPLE_SUB)  # reference sample CSV
SUBMISSION_MODEL = str(SUBMISSION).replace(".csv", f"_{LLM_MODEL}_T{TEMPERATURE}_R{RUN}.csv")

# --- load reference columns ---
sample_df = pd.read_csv(sample_csv)
cols_order = sample_df.columns.tolist()  # only columns to keep, including PXD and ID

# --- iterate SDRF CSVs ---
all_dfs = []
text_dir = Path(TEST_TEXT_DIR)
files = sorted(text_dir.glob("PXD*.json"))
# we want them same order as in the text dor
for i, jf in enumerate(files, 1):
    pxd = jf.name.split("_")[0]
    # Extract PXD from filename
    f = output_folder / f"{pxd}_PubText.sdrf.csv"
    df = pd.read_csv(f)
    # Extract PXD from filename
    try:
        #pxd = f.stem.split("_")[0]
        df["PXD"] = pxd  # fill the PXD column
        all_dfs.append(df)
    except Exception as err:
        log.error(err)
    
# --- concatenate all files ---
combined_df = pd.concat(all_dfs, ignore_index=True)

# --- ensure all sample columns exist ---
for c in cols_order:
    if c not in combined_df.columns:
        combined_df[c] = pd.NA

# --- assign consecutive IDs ---
if "ID" in cols_order:
    combined_df["ID"] = range(1, len(combined_df) + 1)

# --- keep only columns from sample CSV and in order ---
combined_df = combined_df[cols_order]
# no idea, but this is in SampleSubmission
combined_df['Usage'] = ['Public' if i % 2 == 0 else 'Private' for i in range(len(combined_df))]
combined_df = combined_df.replace('not applicable', 'Not Applicable')

# not all factors are same as characteristics
# it's more complicated to be handled later 
# do not override fv , LLM should handle them in main
#fv_headers = ["Bait","CellPart","Compound","Disease","FractionIdentifier","GeneticModification","Temperature","Treatment"]
#for fv in fv_headers:
#    c = 'Comment' if fv == "FractionIdentifier" else 'Characteristics'
#    combined_df[f'FactorValue[{fv}]'] = combined_df[f'{c}[{fv}]'] 

# defaults, mandatory for proteomics
mandatory_col = "Characteristics[CleavageAgent]"
combined_df.loc[combined_df[mandatory_col] == "Not Applicable", mandatory_col] = "AC=MS:1001251; NT=Trypsin"
mandatory_col = "Comment[AcquisitionMethod]"
combined_df.loc[combined_df[mandatory_col] == "Not Applicable", mandatory_col] = "DDA"

# ---  save final combined CSV ---
combined_df.to_csv(SUBMISSION_MODEL, index=False)
print(f"Combined SDRF dataframe saved -> {SUBMISSION_MODEL} dataset shape {combined_df.shape}")

Combined SDRF dataframe saved -> /kaggle/working/submission_gemma-3-4b-it_T0_R3.csv dataset shape (1659, 81)

## Normalise with keyword maps and Ontology Lookup Service 
using sdrf_pipeline.ols and modelmess cv_map

In [26]:
from src.cv_map import build_cv_normaliser, normalise_submission
cv_normalizer = build_cv_normaliser(use_ols=True) 
assert "NT=Orbitrap;AC=MS:1000484", cv_normalizer.normalise('Comment[MS2MassAnalyzer]', 'Orbitrap')

assert "Homo sapiens" ==  cv_normalizer.normalise('Characteristics[Organism]', 'human')
assert "Homo sapiens" ==  cv_normalizer.normalise('Characteristics[Organism]', "Homo sapiens")
print(cv_normalizer.normalise('Characteristics[Sex]', "fEmale"))
print(cv_normalizer.normalise('Characteristics[CellLine]', "HeLa"))
print(cv_normalizer.normalise('Characteristics[CellType]', "HeLa"))

2026-03-30 11:43:41,067 INFO No cached ontology files found. Downloading from GitHub...
2026-03-30 11:43:41,067 INFO Downloading ontology file: bto.parquet
Downloading file 'bto.parquet' from 'https://raw.githubusercontent.com/bigbio/sdrf-pipelines/v0.1.2/data/ontologies/bto.parquet' to '/root/.cache/sdrf-pipelines/ontologies'.
2026-03-30 11:43:41,392 INFO Successfully cached: /root/.cache/sdrf-pipelines/ontologies/bto.parquet
2026-03-30 11:43:41,393 INFO Downloading ontology file: chebi.parquet
Downloading file 'chebi.parquet' from 'https://raw.githubusercontent.com/bigbio/sdrf-pipelines/v0.1.2/data/ontologies/chebi.parquet' to '/root/.cache/sdrf-pipelines/ontologies'.
2026-03-30 11:43:41,750 INFO Successfully cached: /root/.cache/sdrf-pipelines/ontologies/chebi.parquet
2026-03-30 11:43:41,750 INFO Downloading ontology file: cl.parquet
Downloading file 'cl.parquet' from 'https://raw.githubusercontent.com/bigbio/sdrf-pipelines/v0.1.2/data/ontologies/cl.parquet' to '/root/.cache/sdrf-pipelines/ontologies'.
2026-03-30 11:43:42,098 INFO Successfully cached: /root/.cache/sdrf-pipelines/ontologies/cl.parquet
2026-03-30 11:43:42,099 INFO Downloading ontology file: clo.parquet
Downloading file 'clo.parquet' from 'https://raw.githubusercontent.com/bigbio/sdrf-pipelines/v0.1.2/data/ontologies/clo.parquet' to '/root/.cache/sdrf-pipelines/ontologies'.
2026-03-30 11:43:42,538 INFO Successfully cached: /root/.cache/sdrf-pipelines/ontologies/clo.parquet
2026-03-30 11:43:42,538 INFO Downloading ontology file: doid.parquet
Downloading file 'doid.parquet' from 'https://raw.githubusercontent.com/bigbio/sdrf-pipelines/v0.1.2/data/ontologies/doid.parquet' to '/root/.cache/sdrf-pipelines/ontologies'.
2026-03-30 11:43:42,817 INFO Successfully cached: /root/.cache/sdrf-pipelines/ontologies/doid.parquet
2026-03-30 11:43:42,818 INFO Downloading ontology file: efo.parquet
Downloading file 'efo.parquet' from 'https://raw.githubusercontent.com/bigbio/sdrf-pipelines/v0.1.2/data/ontologies/efo.parquet' to '/root/.cache/sdrf-pipelines/ontologies'.
2026-03-30 11:43:43,461 INFO Successfully cached: /root/.cache/sdrf-pipelines/ontologies/efo.parquet
2026-03-30 11:43:43,462 INFO Downloading ontology file: envo.parquet
Downloading file 'envo.parquet' from 'https://raw.githubusercontent.com/bigbio/sdrf-pipelines/v0.1.2/data/ontologies/envo.parquet' to '/root/.cache/sdrf-pipelines/ontologies'.
2026-03-30 11:43:43,649 INFO Successfully cached: /root/.cache/sdrf-pipelines/ontologies/envo.parquet
2026-03-30 11:43:43,650 INFO Downloading ontology file: gaz.parquet
Downloading file 'gaz.parquet' from 'https://raw.githubusercontent.com/bigbio/sdrf-pipelines/v0.1.2/data/ontologies/gaz.parquet' to '/root/.cache/sdrf-pipelines/ontologies'.
2026-03-30 11:43:44,372 INFO Successfully cached: /root/.cache/sdrf-pipelines/ontologies/gaz.parquet
2026-03-30 11:43:44,372 INFO Downloading ontology file: hancestro.parquet
Downloading file 'hancestro.parquet' from 'https://raw.githubusercontent.com/bigbio/sdrf-pipelines/v0.1.2/data/ontologies/hancestro.parquet' to '/root/.cache/sdrf-pipelines/ontologies'.
2026-03-30 11:43:44,539 INFO Successfully cached: /root/.cache/sdrf-pipelines/ontologies/hancestro.parquet
2026-03-30 11:43:44,539 INFO Downloading ontology file: mod.parquet
Downloading file 'mod.parquet' from 'https://raw.githubusercontent.com/bigbio/sdrf-pipelines/v0.1.2/data/ontologies/mod.parquet' to '/root/.cache/sdrf-pipelines/ontologies'.
2026-03-30 11:43:44,737 INFO Successfully cached: /root/.cache/sdrf-pipelines/ontologies/mod.parquet
2026-03-30 11:43:44,738 INFO Downloading ontology file: mondo.parquet
Downloading file 'mondo.parquet' from 'https://raw.githubusercontent.com/bigbio/sdrf-pipelines/v0.1.2/data/ontologies/mondo.parquet' to '/root/.cache/sdrf-pipelines/ontologies'.
2026-03-30 11:43:45,287 INFO Successfully cached: /root/.cache/sdrf-pipelines/ontologies/mondo.parquet
2026-03-30 11:43:45,287 INFO Downloading ontology file: ncbitaxon.parquet
Downloading file 'ncbitaxon.parquet' from 'https://raw.githubusercontent.com/bigbio/sdrf-pipelines/v0.1.2/data/ontologies/ncbitaxon.parquet' to '/root/.cache/sdrf-pipelines/ontologies'.
2026-03-30 11:43:47,158 INFO Successfully cached: /root/.cache/sdrf-pipelines/ontologies/ncbitaxon.parquet
2026-03-30 11:43:47,159 INFO Downloading ontology file: ncit.parquet
Downloading file 'ncit.parquet' from 'https://raw.githubusercontent.com/bigbio/sdrf-pipelines/v0.1.2/data/ontologies/ncit.parquet' to '/root/.cache/sdrf-pipelines/ontologies'.
2026-03-30 11:43:47,775 INFO Successfully cached: /root/.cache/sdrf-pipelines/ontologies/ncit.parquet
2026-03-30 11:43:47,776 INFO Downloading ontology file: pato.parquet
Downloading file 'pato.parquet' from 'https://raw.githubusercontent.com/bigbio/sdrf-pipelines/v0.1.2/data/ontologies/pato.parquet' to '/root/.cache/sdrf-pipelines/ontologies'.
2026-03-30 11:43:47,952 INFO Successfully cached: /root/.cache/sdrf-pipelines/ontologies/pato.parquet
2026-03-30 11:43:47,953 INFO Downloading ontology file: pride.parquet
Downloading file 'pride.parquet' from 'https://raw.githubusercontent.com/bigbio/sdrf-pipelines/v0.1.2/data/ontologies/pride.parquet' to '/root/.cache/sdrf-pipelines/ontologies'.
2026-03-30 11:43:48,146 INFO Successfully cached: /root/.cache/sdrf-pipelines/ontologies/pride.parquet
2026-03-30 11:43:48,147 INFO Downloading ontology file: psi-ms.parquet
Downloading file 'psi-ms.parquet' from 'https://raw.githubusercontent.com/bigbio/sdrf-pipelines/v0.1.2/data/ontologies/psi-ms.parquet' to '/root/.cache/sdrf-pipelines/ontologies'.
2026-03-30 11:43:48,362 INFO Successfully cached: /root/.cache/sdrf-pipelines/ontologies/psi-ms.parquet
2026-03-30 11:43:48,363 INFO Downloading ontology file: uberon.parquet
Downloading file 'uberon.parquet' from 'https://raw.githubusercontent.com/bigbio/sdrf-pipelines/v0.1.2/data/ontologies/uberon.parquet' to '/root/.cache/sdrf-pipelines/ontologies'.
2026-03-30 11:43:48,749 INFO Successfully cached: /root/.cache/sdrf-pipelines/ontologies/uberon.parquet
2026-03-30 11:43:48,750 INFO Downloading ontology file: unimod.parquet
Downloading file 'unimod.parquet' from 'https://raw.githubusercontent.com/bigbio/sdrf-pipelines/v0.1.2/data/ontologies/unimod.parquet' to '/root/.cache/sdrf-pipelines/ontologies'.
2026-03-30 11:43:48,937 INFO Successfully cached: /root/.cache/sdrf-pipelines/ontologies/unimod.parquet
2026-03-30 11:43:48,937 INFO Successfully downloaded 18 ontology files
2026-03-30 11:43:48,938 INFO Found 18 ontology cache files: bto, chebi, cl, clo, doid, efo, envo, gaz, hancestro, mod, mondo, ncbitaxon, ncit, pato, pride, psi-ms, uberon, unimod
2026-03-30 11:43:48,939 INFO Using Dict cache backend
2026-03-30 11:43:48,939 INFO OLS cache loaded

female
hela
HeLa

#### Make sure this warning disappears - otherwise we are not using the Ontology Lookup Service

WARNING OLS dependencies not available — using keyword maps only

### Normalise

In [27]:
from src.eval import dataframe_diff, score, print_column_value_diffs
submission_df = pd.read_csv(SUBMISSION_MODEL)
SUBMISSION_NORM = str(SUBMISSION_MODEL).replace(".csv", "_normalized.csv")
submission_norm = normalise_submission(submission_df, cv_normalizer)
submission_norm.to_csv(SUBMISSION_NORM, index=False)
submission_norm.head()

2026-03-30 11:43:49,177 INFO DictBackend: loaded bto (6566 terms)
2026-03-30 11:43:49,237 INFO DictBackend: loaded unimod (1561 terms)
2026-03-30 11:43:49,324 INFO DictBackend: loaded ms (4015 terms)

,ID,PXD,Raw Data File,Characteristics[Age],Characteristics[AlkylationReagent],Characteristics[AnatomicSiteTumor],Characteristics[AncestryCategory],Characteristics[BMI],Characteristics[Bait],Characteristics[BiologicalReplicate],...,FactorValue[Bait],FactorValue[CellPart],FactorValue[Compound],FactorValue[ConcentrationOfCompound].1,FactorValue[Disease],FactorValue[FractionIdentifier],FactorValue[GeneticModification],FactorValue[Temperature],FactorValue[Treatment],Usage
0,1,PXD004010,ad_pl03.raw,adult,IAA,breast,European,Not Applicable,FLAG-EGFP,3,...,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Public
1,2,PXD004010,ad_pl04.raw,adult,IAA,breast,European,Not Applicable,FLAG-EGFP,4,...,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Private
2,3,PXD004010,ad_pl10.raw,adult,IAA,breast,European,Not Applicable,FLAG-EGFP,10,...,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Public
3,4,PXD004010,ad_pl07.raw,adult,IAA,breast,European,Not Applicable,FLAG-EGFP,7,...,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Private
4,5,PXD004010,ad_pl08.raw,adult,IAA,breast,European,Not Applicable,FLAG-EGFP,8,...,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Not Applicable,Public

### Verify what the normaliser did

In [28]:
from src.eval import score, dataframe_diff, print_column_value_diffs
f1, harm_norm, harm_subm, eval_df = score(submission_norm, submission_df, row_id_column_name="ID")
print(f"## F1={f1}")
display(eval_df.loc[eval_df["f1"]<0.8].head())

diff = dataframe_diff(submission_df, submission_norm)
#diff.to_csv(str(SUBMISSION).replace(".csv", "_normalized_diff.csv"), index=False)
print("## Column differences")
print_column_value_diffs(diff)

## F1=0.8675925925925926

,pxd,AnnotationType,precision,recall,f1,jacc
3,PXD061285,Comment[IonizationType],0.0,0.0,0.0,0.0
7,PXD061285,Characteristics[AlkylationReagent],0.0,0.0,0.0,0.0
16,PXD061285,Characteristics[CellLine],0.0,0.0,0.0,0.0
17,PXD061285,Characteristics[ReductionReagent],0.0,0.0,0.0,0.0
18,PXD061285,Comment[AcquisitionMethod],0.0,0.0,0.0,0.0

## Column differences

Column: Characteristics[AlkylationReagent]
iodoacetamide → IAA
Iodoacetamide → IAA
Chloroacetamide → CAA

Column: Characteristics[CellLine]
ANBL6 → anbl6
HeLa → hela
U2OS → u2os
MCF-7 → mcf7
HEK293T → hek293t
PC3 → pc3

Column: Characteristics[CleavageAgent]
Trypsin/LysC → AC=MS:1001251;NT=Trypsin|AC=MS:1001309;NT=Lys-C
Trypsin → AC=MS:1001251;NT=Trypsin

Column: Characteristics[Label]
label free sample → AC=MS:1002038;NT=label free sample
TMT16-126 → AC=PRIDE:0000543;NT=TMT16plex
TMT16-127N → AC=PRIDE:0000543;NT=TMT16plex
TMT16-127C → AC=PRIDE:0000543;NT=TMT16plex
TMT16-128N → AC=PRIDE:0000543;NT=TMT16plex
TMT16-128C → AC=PRIDE:0000543;NT=TMT16plex
TMT16-129N → AC=PRIDE:0000543;NT=TMT16plex
TMT16-129C → AC=PRIDE:0000543;NT=TMT16plex
TMT16-130N → AC=PRIDE:0000543;NT=TMT16plex
TMT16-130C → AC=PRIDE:0000543;NT=TMT16plex
TMT16-131N → AC=PRIDE:0000543;NT=TMT16plex
TMT16-131C → AC=PRIDE:0000543;NT=TMT16plex
TMT16-132N → AC=PRIDE:0000543;NT=TMT16plex
TMT16-132C → AC=PRIDE:0000543;NT=TMT16plex
TMT16-133N → AC=PRIDE:0000543;NT=TMT16plex
TMT16-133C → AC=PRIDE:0000543;NT=TMT16plex
TMT16-134N → AC=PRIDE:0000543;NT=TMT16plex

Column: Characteristics[Modification]
TMT6plex → NT=tmt6plex;AC=unimod:737
Carbamidomethyl → NT=carbamidomethyl;AC=unimod:4
Phospho → NT=phospho;AC=unimod:21
Oxidation → NT=oxidation;AC=unimod:35

Column: Characteristics[Modification].1
Oxidation → NT=oxidation;AC=unimod:35
Carbamidomethyl → NT=carbamidomethyl;AC=unimod:4

Column: Characteristics[Modification].2
Acetyl → NT=acetyl;AC=unimod:1
Phospho → NT=phospho;AC=unimod:21
Oxidation → NT=oxidation;AC=unimod:35

Column: Characteristics[Modification].3
Phospho → NT=phospho;AC=unimod:21
Acetyl → NT=acetyl;AC=unimod:1

Column: Characteristics[ReductionReagent]
Dithiothreitol → DTT

Column: Comment[AcquisitionMethod]
data-dependent acquisition → DDA
data-independent acquisition → DIA

Column: Comment[FractionationMethod]
gel-based → NT=SDS-PAGE;AC=PRIDE:0000568
SCX → NT=Strong cation-exchange chromatography (SCX);AC=PRIDE:0000561

Column: Comment[FragmentationMethod]
HCD → NT=HCD;AC=MS:1000422
CID → NT=CID;AC=MS:1000133

Column: Comment[Instrument]
Q Exactive HF → AC=MS:1002523;NT=Q Exactive HF
LTQ Orbitrap XL → AC=MS:1000449;NT=LTQ Orbitrap XL
Orbitrap Fusion → AC=MS:1002416;NT=Orbitrap Fusion
Q Exactive → AC=MS:1001911;NT=Q Exactive
TripleTOF 5600 → AC=MS:1002532;NT=TripleTOF 5600
Orbitrap Astral → AC=MS:1003378;NT=Orbitrap Astral

Column: Comment[IonizationType]
ESI → NT=electrospray ionization;AC=MS:1000073

Column: Comment[MS2MassAnalyzer]
Orbitrap → NT=orbitrap;AC=MS:1000484
TOF → NT=time-of-flight;AC=MS:1000084

Column: Comment[Separation]
reverse phase → NT=Reversed-phase chromatography;AC=PRIDE:0000563

In [29]:
SUBMISSION_MODEL

'/kaggle/working/submission_gemma-3-4b-it_T0_R3.csv'

In [30]:
ls -al /kaggle/working/

total 13636
drwxr-xr-x  5 root root    4096 Mar 30 11:08 ./
drwxr-xr-x  6 root root    4096 Mar 30 11:08 ../
drwxr-xr-x  5 root root    4096 Mar 30 11:08 modelmess/
drwxr-xr-x 12 root root    4096 Mar 30 11:08 output_sdrfs/
-rw-r--r--  1 root root 1447283 Mar 30 11:08 submission_deepseek-coder-v2-lite-instruct_T0_R3.csv
-rw-r--r--  1 root root 1865622 Mar 30 11:08 submission_deepseek-coder-v2-lite-instruct_T0_R3_normalized.csv
-rw-r--r--  1 root root 1592679 Mar 30 11:08 submission_gemma-3-12b-it_T0_R3.csv
-rw-r--r--  1 root root 1985458 Mar 30 11:08 submission_gemma-3-12b-it_T0_R3_normalized.csv
-rw-r--r--  1 root root 1457787 Mar 30 11:43 submission_gemma-3-4b-it_T0_R3.csv
-rw-r--r--  1 root root 1855433 Mar 30 11:43 submission_gemma-3-4b-it_T0_R3_normalized.csv
-rw-r--r--  1 root root 1681913 Mar 30 11:08 submission_medgemma-4b-it_T0_R3.csv
-rw-r--r--  1 root root 2045152 Mar 30 11:08 submission_medgemma-4b-it_T0_R3_normalized.csv
drwxr-xr-x  2 root root    4096 Mar 30 11:08 .virtual_documents/

In [31]:
from src.eval import score, dataframe_diff, print_column_value_diffs

# compare with gpt 5.4 if exists

if Path("/kaggle/working/submission_gpt-5.4_T0_R3_normalized.csv").exists():
    
    df1 = pd.read_csv("/kaggle/working/submission_gpt-5.4_T0_R2_normalized.csv")
    df2 = pd.read_csv("/kaggle/working/submission_gpt-5.4_T0_R3_normalized.csv")
    f1, harm_norm, harm_subm, eval_df = score(df1, df2, row_id_column_name="ID")
    print(f"## F1={f1}")
    display(eval_df.loc[eval_df["f1"]<0.8].head())
    
    diff = dataframe_diff(df1, df2)
    if diff.shape[0]==0:
       print("No differences!") 
    else:
        diff.head()
        #diff.to_csv(str(SUBMISSION).replace(".csv", "_normalized_diff.csv"), index=False)
        print("## Column differences")
        print_column_value_diffs(diff)

# Compare with previous submissions

In [32]:
!ls /kaggle/working

modelmess
output_sdrfs
submission_deepseek-coder-v2-lite-instruct_T0_R3.csv
submission_deepseek-coder-v2-lite-instruct_T0_R3_normalized.csv
submission_gemma-3-12b-it_T0_R3.csv
submission_gemma-3-12b-it_T0_R3_normalized.csv
submission_gemma-3-4b-it_T0_R3.csv
submission_gemma-3-4b-it_T0_R3_normalized.csv
submission_medgemma-4b-it_T0_R3.csv
submission_medgemma-4b-it_T0_R3_normalized.csv

In [33]:
def reorder(df, df_reference):
    # Create a tuple key temporarily
    df_keys = list(zip(df['PXD'], df['Raw Data File']))
    ref_keys = list(zip(df_reference['PXD'], df_reference['Raw Data File']))

    # map reference order to df indices
    key_to_index = {}
    for i, k in enumerate(df_keys):
        # allow duplicates: store as list of indices
        key_to_index.setdefault(k, []).append(i)

    # build new order
    new_order = []
    used = {}  # keep track of used duplicates
    for k in ref_keys:
        if k in key_to_index:
            idx_list = key_to_index[k]
            used_count = used.get(k, 0)
            if used_count < len(idx_list):
                new_order.append(idx_list[used_count])
                used[k] = used_count + 1

    # reorder df
    return df.iloc[new_order].reset_index(drop=True)

In [34]:
from src.eval import calculate_fill_stability , suggest_next_fills
next = suggest_next_fills(submission_norm)
display(next)

,PXD,Column,Priority,Suggested_Val,Gain_Potential
261,PXD061195,FactorValue[GeneticModification],Medium (Discovery),LLM_NEEDED,1376
89,PXD061195,Characteristics[Modification].6,Medium (Discovery),LLM_NEEDED,1376
48,PXD061195,Characteristics[GrowthRate],Medium (Discovery),LLM_NEEDED,1376
63,PXD061195,Characteristics[Modification].4,Medium (Discovery),LLM_NEEDED,1376
246,PXD061195,FactorValue[FractionIdentifier],Medium (Discovery),LLM_NEEDED,1376
...,...,...,...,...,...
62,PXD061136,Characteristics[Modification].4,Medium (Discovery),LLM_NEEDED,2
243,PXD061009,FactorValue[FractionIdentifier],Medium (Discovery),LLM_NEEDED,2
245,PXD061136,FactorValue[FractionIdentifier],Medium (Discovery),LLM_NEEDED,2
258,PXD061009,FactorValue[GeneticModification],Medium (Discovery),LLM_NEEDED,2
260,PXD061136,FactorValue[GeneticModification],Medium (Discovery),LLM_NEEDED,2

In [35]:
from src.postprocessing import competition_aware_merge, merge_with_similarity
from src.eval import calculate_fill_stability , suggest_next_fills

BEST_SO_FAR = Path("/kaggle/input/datasets/n10705013/best-hdd2026-submissions-rule-first-then-llm")
for f in BEST_SO_FAR.glob("*.csv"):
    df = pd.read_csv(f)[sample_df.columns]
    submission_norm_same_order = reorder(submission_norm, df)
    print(f"=== {f.name} ===")
    f1, harm_norm, harm_subm, eval_df = score(df, submission_norm_same_order, row_id_column_name="ID")
    print(f"=== {f1} {f.name}")
    display(eval_df.loc[eval_df["f1"]<0.8].head())
    diff = dataframe_diff(df, submission_norm_same_order)
    #print_column_value_diffs(diff)    
    #submission_norm_same_order.to_csv("/kaggle/working/debug.csv", index=False)

    #let's merge , fill in the gaps with the best one and see if it improves
    df_merged = competition_aware_merge(df_peak=submission_norm_same_order, df_new=df)
    result = calculate_fill_stability(submission_norm_same_order, df)
    f1_merged, harm_norm, harm_subm, eval_df_merged = score(df, df_merged, row_id_column_name="ID")
    print(f"=== F1={f1} {f.name} --> F1={f1_merged} (merged)")
    print(result)
    next = suggest_next_fills(df_merged)
    display(next)
    #next.to_csv(str(SUBMISSION).replace(".csv","_next.csv"))

=== localai_submission_gemma-3-4b-it_T0_R3_normalized.csv ===
=== 0.8747300215982722 localai_submission_gemma-3-4b-it_T0_R3_normalized.csv

          pxd                    AnnotationType  precision  recall   f1  jacc
3   PXD061285              FactorValue[Disease]        0.0     0.0  0.0   0.0
7   PXD061285                 FactorValue[Bait]        0.0     0.0  0.0   0.0
22  PXD061285   FactorValue[FractionIdentifier]        0.0     0.0  0.0   0.0
23  PXD061285  FactorValue[GeneticModification]        0.0     0.0  0.0   0.0
30  PXD025663              FactorValue[Disease]        0.0     0.0  0.0   0.0

--- Metric Analysis ---
Recall Gains: 13032 holes filled.
Precision Risks: 0 clusters broken.
=== F1=0.8747300215982722 localai_submission_gemma-3-4b-it_T0_R3_normalized.csv --> F1=1.0 (merged)
{'gains': 13032, 'corruptions': 0, 'perfect': 89952}

,PXD,Column,Priority,Suggested_Val,Gain_Potential
15,PXD061195,Characteristics[BMI],Medium (Discovery),LLM_NEEDED,1376
39,PXD061195,Characteristics[DiseaseTreatment],Medium (Discovery),LLM_NEEDED,1376
48,PXD061195,Characteristics[GrowthRate],Medium (Discovery),LLM_NEEDED,1376
32,PXD061195,Characteristics[DevelopmentalStage],Medium (Discovery),LLM_NEEDED,1376
27,PXD061195,Characteristics[Depletion],Medium (Discovery),LLM_NEEDED,1376
...,...,...,...,...,...
150,PXD061136,Comment[CollisionEnergy],Medium (Discovery),LLM_NEEDED,2
158,PXD061136,Comment[FragmentMassTolerance],Medium (Discovery),LLM_NEEDED,2
153,PXD061136,Comment[EnrichmentMethod],Medium (Discovery),LLM_NEEDED,2
172,PXD061136,FactorValue[ConcentrationOfCompound].1,Medium (Discovery),LLM_NEEDED,2
170,PXD061009,FactorValue[ConcentrationOfCompound].1,Medium (Discovery),LLM_NEEDED,2

=== submission_bggpt-gemma-3-27b-fp8_gpt-4o-mini123.csv ===
=== 0.53330142882166 submission_bggpt-gemma-3-27b-fp8_gpt-4o-mini123.csv

         pxd                      AnnotationType  precision  recall   f1  jacc
0  PXD061285                FactorValue[Disease]        0.0     0.0  0.0   0.0
2  PXD061285  Characteristics[OriginSiteDisease]        0.0     0.0  0.0   0.0
3  PXD061285           Characteristics[Staining]        0.0     0.0  0.0   0.0
4  PXD061285               FactorValue[CellPart]        0.0     0.0  0.0   0.0
6  PXD061285                   FactorValue[Bait]        0.0     0.0  0.0   0.0

/kaggle/working/modelmess/sdrf_pipeline/src/postprocessing.py:233: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  result.loc[mask, col] = df_new.loc[mask, col]

--- Metric Analysis ---
Recall Gains: 17758 holes filled.
Precision Risks: 33950 clusters broken.
=== F1=0.53330142882166 submission_bggpt-gemma-3-27b-fp8_gpt-4o-mini123.csv --> F1=0.7208736831569201 (merged)
{'gains': 17758, 'corruptions': 33950, 'perfect': 56002}

,PXD,Column,Priority,Suggested_Val,Gain_Potential
30,PXD061195,Characteristics[DiseaseTreatment],Medium (Discovery),LLM_NEEDED,1376
21,PXD061195,Characteristics[Depletion],Medium (Discovery),LLM_NEEDED,1376
24,PXD061195,Characteristics[DevelopmentalStage],Medium (Discovery),LLM_NEEDED,1376
35,PXD061195,Characteristics[GrowthRate],Medium (Discovery),LLM_NEEDED,1376
14,PXD061195,Characteristics[BMI],Medium (Discovery),LLM_NEEDED,1376
...,...,...,...,...,...
104,PXD061136,Characteristics[TumorGrade],Medium (Discovery),LLM_NEEDED,2
145,PXD061136,FactorValue[ConcentrationOfCompound].1,Medium (Discovery),LLM_NEEDED,2
143,PXD061009,FactorValue[ConcentrationOfCompound].1,Medium (Discovery),LLM_NEEDED,2
136,PXD061136,FactorValue[Compound],Medium (Discovery),LLM_NEEDED,2
163,PXD061136,FactorValue[Treatment],Medium (Discovery),LLM_NEEDED,2

=== claude-sonnet-4.6_R1_normalised.csv ===
=== 0.6145119597106352 claude-sonnet-4.6_R1_normalised.csv

         pxd             AnnotationType  precision  recall   f1  jacc
0  PXD061285       FactorValue[Disease]        0.0     0.0  0.0   0.0
2  PXD061285  Characteristics[Staining]        0.0     0.0  0.0   0.0
4  PXD061285      FactorValue[CellPart]        0.0     0.0  0.0   0.0
5  PXD061285       Characteristics[Sex]        0.0     0.0  0.0   0.0
8  PXD061285          FactorValue[Bait]        0.0     0.0  0.0   0.0

/kaggle/working/modelmess/sdrf_pipeline/src/postprocessing.py:233: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  result.loc[mask, col] = df_new.loc[mask, col]

--- Metric Analysis ---
Recall Gains: 15078 holes filled.
Precision Risks: 42708 clusters broken.
=== F1=0.6145119597106352 claude-sonnet-4.6_R1_normalised.csv --> F1=0.7707531798591402 (merged)
{'gains': 15078, 'corruptions': 42708, 'perfect': 47244}

,PXD,Column,Priority,Suggested_Val,Gain_Potential
62,PXD061195,Characteristics[Modification].5,Medium (Discovery),LLM_NEEDED,1376
24,PXD061195,Characteristics[Depletion],Medium (Discovery),LLM_NEEDED,1376
26,PXD061195,Characteristics[DevelopmentalStage],Medium (Discovery),LLM_NEEDED,1376
32,PXD061195,Characteristics[DiseaseTreatment],Medium (Discovery),LLM_NEEDED,1376
14,PXD061195,Characteristics[BMI],Medium (Discovery),LLM_NEEDED,1376
...,...,...,...,...,...
167,PXD061136,FactorValue[ConcentrationOfCompound].1,Medium (Discovery),LLM_NEEDED,2
180,PXD061136,FactorValue[GeneticModification],Medium (Discovery),LLM_NEEDED,2
165,PXD061009,FactorValue[ConcentrationOfCompound].1,Medium (Discovery),LLM_NEEDED,2
186,PXD061009,FactorValue[Temperature],Medium (Discovery),LLM_NEEDED,2
193,PXD061136,FactorValue[Treatment],Medium (Discovery),LLM_NEEDED,2

=== gpt-5.4_submission_gpt-4o-mini_merged_26.csv ===
=== 0.5617585272407608 gpt-5.4_submission_gpt-4o-mini_merged_26.csv

,pxd,AnnotationType,precision,recall,f1,jacc
0,PXD061285,FactorValue[Disease],0.0,0.0,0.0,0.0
2,PXD061285,Characteristics[Staining],0.0,0.0,0.0,0.0
4,PXD061285,FactorValue[CellPart],0.0,0.0,0.0,0.0
5,PXD061285,Characteristics[Sex],0.0,0.0,0.0,0.0
11,PXD061285,Characteristics[GeneticModification],0.0,0.0,0.0,0.0

/kaggle/working/modelmess/sdrf_pipeline/src/postprocessing.py:233: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  result.loc[mask, col] = df_new.loc[mask, col]

--- Metric Analysis ---
Recall Gains: 19134 holes filled.
Precision Risks: 44800 clusters broken.
=== F1=0.5617585272407608 gpt-5.4_submission_gpt-4o-mini_merged_26.csv --> F1=0.7351750712156804 (merged)
{'gains': 19134, 'corruptions': 44800, 'perfect': 45152}

,PXD,Column,Priority,Suggested_Val,Gain_Potential
14,PXD061195,Characteristics[BMI],Medium (Discovery),LLM_NEEDED,1376
22,PXD061195,Characteristics[Depletion],Medium (Discovery),LLM_NEEDED,1376
24,PXD061195,Characteristics[DevelopmentalStage],Medium (Discovery),LLM_NEEDED,1376
37,PXD061195,Characteristics[GrowthRate],Medium (Discovery),LLM_NEEDED,1376
29,PXD061195,Characteristics[DiseaseTreatment],Medium (Discovery),LLM_NEEDED,1376
...,...,...,...,...,...
164,PXD061009,FactorValue[ConcentrationOfCompound].1,Medium (Discovery),LLM_NEEDED,2
166,PXD061136,FactorValue[ConcentrationOfCompound].1,Medium (Discovery),LLM_NEEDED,2
177,PXD061009,FactorValue[GeneticModification],Medium (Discovery),LLM_NEEDED,2
186,PXD061136,FactorValue[Treatment],Medium (Discovery),LLM_NEEDED,2
185,PXD061009,FactorValue[Treatment],Medium (Discovery),LLM_NEEDED,2

=== submission_2535.csv ===
=== 0.580109188948968 submission_2535.csv

         pxd                 AnnotationType  precision  recall        f1  jacc
0  PXD061285  Characteristics[Modification]        0.5    0.25  0.333333   0.5
3  PXD061285           FactorValue[Disease]        0.0    0.00  0.000000   0.0
4  PXD061285      Characteristics[Staining]        0.0    0.00  0.000000   0.0
6  PXD061285  Characteristics[PooledSample]        0.0    0.00  0.000000   0.0
7  PXD061285          FactorValue[CellPart]        0.0    0.00  0.000000   0.0

/kaggle/working/modelmess/sdrf_pipeline/src/postprocessing.py:233: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  result.loc[mask, col] = df_new.loc[mask, col]

--- Metric Analysis ---
Recall Gains: 18350 holes filled.
Precision Risks: 46892 clusters broken.
=== F1=0.580109188948968 submission_2535.csv --> F1=0.7320229596472692 (merged)
{'gains': 18350, 'corruptions': 46892, 'perfect': 43060}

,PXD,Column,Priority,Suggested_Val,Gain_Potential
15,PXD061195,Characteristics[BMI],Medium (Discovery),LLM_NEEDED,1376
35,PXD061195,Characteristics[DiseaseTreatment],Medium (Discovery),LLM_NEEDED,1376
43,PXD061195,Characteristics[GrowthRate],Medium (Discovery),LLM_NEEDED,1376
26,PXD061195,Characteristics[Depletion],Medium (Discovery),LLM_NEEDED,1376
28,PXD061195,Characteristics[DevelopmentalStage],Medium (Discovery),LLM_NEEDED,1376
...,...,...,...,...,...
178,PXD061009,FactorValue[ConcentrationOfCompound].1,Medium (Discovery),LLM_NEEDED,2
198,PXD061009,FactorValue[Temperature],Medium (Discovery),LLM_NEEDED,2
193,PXD061136,FactorValue[GeneticModification],Medium (Discovery),LLM_NEEDED,2
206,PXD061136,FactorValue[Treatment],Medium (Discovery),LLM_NEEDED,2
205,PXD061009,FactorValue[Treatment],Medium (Discovery),LLM_NEEDED,2

# Archive

In [36]:
!zip -r {OUTPUT_DIR}.zip {OUTPUT_DIR}

updating: kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/ (stored 0%)
updating: kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD019519_PubText.sdrf.csv (deflated 85%)
updating: kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD050621_PubText.sdrf.json (deflated 96%)
updating: kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD061009_PubText.sdrf.json (deflated 82%)
updating: kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD061090_PubText.sdrf.json (deflated 93%)
updating: kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD061285_PubText.sdrf.csv (deflated 97%)
updating: kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD061009_PubText.sdrf.csv (deflated 74%)
updating: kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD064564_PubText.sdrf.json (deflated 97%)
updating: kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD025663_PubText.sdrf.csv (deflated 91%)
updating: kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD061285_PubText.sdrf.json (deflated 98%)
updating: kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD062877_PubText.sdrf.csv (deflated 96%)
updating: kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD061136_PubText.sdrf.json (deflated 85%)
updating: kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD040582_PubText.sdrf.csv (deflated 94%)
updating: kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD040582_PubText.sdrf.json (deflated 97%)
updating: kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD061195_PubText.sdrf.csv (deflated 99%)
updating: kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD062877_PubText.sdrf.json (deflated 98%)
updating: kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD050621_PubText.sdrf.csv (deflated 91%)
updating: kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD004010_PubText.sdrf.json (deflated 96%)
updating: kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD016436_PubText.sdrf.json (deflated 97%)
updating: kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD061090_PubText.sdrf.csv (deflated 85%)
updating: kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD004010_PubText.sdrf.csv (deflated 91%)
updating: kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD062014_PubText.sdrf.json (deflated 98%)
updating: kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD064564_PubText.sdrf.csv (deflated 95%)
updating: kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD062469_PubText.sdrf.json (deflated 98%)
updating: kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD025663_PubText.sdrf.json (deflated 96%)
updating: kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD019519_PubText.sdrf.json (deflated 93%)
updating: kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD061195_PubText.sdrf.json (deflated 99%)
updating: kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD062469_PubText.sdrf.csv (deflated 96%)
updating: kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD062014_PubText.sdrf.csv (deflated 95%)
updating: kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD061136_PubText.sdrf.csv (deflated 79%)
updating: kaggle/working/output_sdrfs/gemma-3-4b-it/T0/R1/PXD016436_PubText.sdrf.csv (deflated 93%)

In [37]:
if server:
    server.stop()

LocalAI server stopped.

In [38]:
end_time = time.monotonic()
print("Execution time [HH:MM:SS.ms]:", timedelta(seconds = end_time - start_time))
print("Execution time [seconds]:", round(timedelta(seconds = end_time - start_time).total_seconds()))

Execution time [HH:MM:SS.ms]: 0:36:17.536168
Execution time [seconds]: 2178